package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.general.FormFlag;
import com.kiun.functionary.base.general.FormType;
import com.kiun.functionary.base.general.ListBuild;
import com.kiun.functionary.base.general.ListBuildItem;
import com.kiun.functionary.dao.IdRandom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * 机构
 *
 * gks_agency
 *
 * 2023-12-28 17:53:09
 */
@ApiModel(description="机构")
@ListBuild(value = "Agency", title = "机构")
public class Agency extends IdRandom {
    /**
     * 机构ID
     */
    @ApiModelProperty("机构ID")
    @ListBuildItem(title = "机构ID", flag = FormFlag.Edit|FormFlag.AddDisable|FormFlag.EditDisable)
    private String id;

    /**
     * 机构名称
     */
    @ApiModelProperty("机构名称")
    @ListBuildItem(title = "机构名称")
    private String name;

    /**
     * 机构简称标题
     */
    @ApiModelProperty("机构简称标题")
    @ListBuildItem(title = "机构简称标题")
    private String title;

    /**
     * 描述
     */
    @ApiModelProperty("描述")
    @ListBuildItem(title = "描述")
    private String desc;

    /**
     * 机构图标
     */
    @ApiModelProperty("机构图标")
    @ListBuildItem(title = "机构图标", type = FormType.Image)
    private String logo;

    /**
     * 管理员ID
     */
    @ApiModelProperty("管理员")
    @ListBuildItem(title = "管理员")
    private String admin;

    /**
     */
    private String addUserId;

    /**
     */
    private String addUserNm;

    /**
     * 添加时间
     */
    private Date addTime;

    /**
     */
    private String updUserId;

    /**
     */
    private String updUserNm;

    /**
     * 修改时间
     */
    private Date updTime;

    /**
     */
    private String updTerminalIp;
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    public String getAdmin() {
        return admin;
    }

    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    public String getAddUserId() {
        return addUserId;
    }

    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    public String getAddUserNm() {
        return addUserNm;
    }

    public void setAddUserNm(String addUserNm) {
        this.addUserNm = addUserNm == null ? null : addUserNm.trim();
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getUpdUserId() {
        return updUserId;
    }

    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId == null ? null : updUserId.trim();
    }

    public String getUpdUserNm() {
        return updUserNm;
    }

    public void setUpdUserNm(String updUserNm) {
        this.updUserNm = updUserNm == null ? null : updUserNm.trim();
    }

    public Date getUpdTime() {
        return updTime;
    }

    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    public String getUpdTerminalIp() {
        return updTerminalIp;
    }

    public void setUpdTerminalIp(String updTerminalIp) {
        this.updTerminalIp = updTerminalIp == null ? null : updTerminalIp.trim();
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_agency
     * 2023-12-25 22:16:47
     */
    public void setId(String id) {
        this.id=id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_agency
     * 2023-12-25 22:16:47
     */
    public String getId() {
        return id;
    }
}
