package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.general.ListBuild;
import com.kiun.functionary.base.general.ListBuildItem;
import com.kiun.functionary.dao.IdRandom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * 反馈记录
 *
 * gks_feedback
 *
 * 2023-09-27 17:17:31
 */
@ApiModel(description="反馈记录")
@ListBuild(value = "Feedback", title = "反馈记录")
public class Feedback extends IdRandom {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    @ListBuildItem(title = "主键")
    private String id;

    /**
     * 反馈
     */
    @ApiModelProperty("反馈")
    @ListBuildItem(title = "反馈")
    private String feedback;

    /**
     */
    @ApiModelProperty("")
    @ListBuildItem(title = "")
    private String addUserId;

    /**
     */
    @ApiModelProperty("")
    @ListBuildItem(title = "")
    private String addUserNm;

    /**
     * 添加时间
     */
    @ApiModelProperty("添加时间")
    @ListBuildItem(title = "添加时间")
    private Date addTime;

    /**
     */
    @ApiModelProperty("")
    @ListBuildItem(title = "")
    private String updUserId;

    /**
     */
    @ApiModelProperty("")
    @ListBuildItem(title = "")
    private String updUserNm;

    /**
     * 修改时间
     */
    @ApiModelProperty("修改时间")
    @ListBuildItem(title = "修改时间")
    private Date updTime;

    /**
     */
    @ApiModelProperty("")
    @ListBuildItem(title = "")
    private String updTerminalIp;

    public String getFeedback() {
        return feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    public String getAddUserId() {
        return addUserId;
    }

    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    public String getAddUserNm() {
        return addUserNm;
    }

    public void setAddUserNm(String addUserNm) {
        this.addUserNm = addUserNm == null ? null : addUserNm.trim();
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getUpdUserId() {
        return updUserId;
    }

    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId == null ? null : updUserId.trim();
    }

    public String getUpdUserNm() {
        return updUserNm;
    }

    public void setUpdUserNm(String updUserNm) {
        this.updUserNm = updUserNm == null ? null : updUserNm.trim();
    }

    public Date getUpdTime() {
        return updTime;
    }

    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    public String getUpdTerminalIp() {
        return updTerminalIp;
    }

    public void setUpdTerminalIp(String updTerminalIp) {
        this.updTerminalIp = updTerminalIp == null ? null : updTerminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_feedback
     * 2023-09-27 17:17:31
     */
    public void setId(String id) {
        this.id=id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_feedback
     * 2023-09-27 17:17:31
     */
    public String getId() {
        return id;
    }
}
