package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.Criterion;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobDetailsExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-08-08 23:13:18
     */
    protected boolean distinct;

    /**
     * 2023-08-08 23:13:18
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public JobDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIsNull() {
            addCriterion("job_notice is null");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIsNotNull() {
            addCriterion("job_notice is not null");
            return (Criteria) this;
        }

        public Criteria andJobNoticeEqualTo(String value) {
            addCriterion("job_notice =", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotEqualTo(String value) {
            addCriterion("job_notice <>", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeGreaterThan(String value) {
            addCriterion("job_notice >", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("job_notice >=", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLessThan(String value) {
            addCriterion("job_notice <", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLessThanOrEqualTo(String value) {
            addCriterion("job_notice <=", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLike(String value) {
            addCriterion("job_notice like", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotLike(String value) {
            addCriterion("job_notice not like", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIn(List<String> values) {
            addCriterion("job_notice in", values, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotIn(List<String> values) {
            addCriterion("job_notice not in", values, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeBetween(String value1, String value2) {
            addCriterion("job_notice between", value1, value2, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotBetween(String value1, String value2) {
            addCriterion("job_notice not between", value1, value2, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobCountIsNull() {
            addCriterion("job_count is null");
            return (Criteria) this;
        }

        public Criteria andJobCountIsNotNull() {
            addCriterion("job_count is not null");
            return (Criteria) this;
        }

        public Criteria andJobCountEqualTo(Integer value) {
            addCriterion("job_count =", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotEqualTo(Integer value) {
            addCriterion("job_count <>", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountGreaterThan(Integer value) {
            addCriterion("job_count >", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_count >=", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountLessThan(Integer value) {
            addCriterion("job_count <", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountLessThanOrEqualTo(Integer value) {
            addCriterion("job_count <=", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountIn(List<Integer> values) {
            addCriterion("job_count in", values, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotIn(List<Integer> values) {
            addCriterion("job_count not in", values, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountBetween(Integer value1, Integer value2) {
            addCriterion("job_count between", value1, value2, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotBetween(Integer value1, Integer value2) {
            addCriterion("job_count not between", value1, value2, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNull() {
            addCriterion("job_salary is null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNotNull() {
            addCriterion("job_salary is not null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryEqualTo(BigDecimal value) {
            addCriterion("job_salary =", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotEqualTo(BigDecimal value) {
            addCriterion("job_salary <>", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThan(BigDecimal value) {
            addCriterion("job_salary >", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("job_salary >=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThan(BigDecimal value) {
            addCriterion("job_salary <", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("job_salary <=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIn(List<BigDecimal> values) {
            addCriterion("job_salary in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotIn(List<BigDecimal> values) {
            addCriterion("job_salary not in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_salary between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_salary not between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobRequireIsNull() {
            addCriterion("job_require is null");
            return (Criteria) this;
        }

        public Criteria andJobRequireIsNotNull() {
            addCriterion("job_require is not null");
            return (Criteria) this;
        }

        public Criteria andJobRequireEqualTo(String value) {
            addCriterion("job_require =", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotEqualTo(String value) {
            addCriterion("job_require <>", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireGreaterThan(String value) {
            addCriterion("job_require >", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireGreaterThanOrEqualTo(String value) {
            addCriterion("job_require >=", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLessThan(String value) {
            addCriterion("job_require <", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLessThanOrEqualTo(String value) {
            addCriterion("job_require <=", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLike(String value) {
            addCriterion("job_require like", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotLike(String value) {
            addCriterion("job_require not like", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireIn(List<String> values) {
            addCriterion("job_require in", values, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotIn(List<String> values) {
            addCriterion("job_require not in", values, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireBetween(String value1, String value2) {
            addCriterion("job_require between", value1, value2, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotBetween(String value1, String value2) {
            addCriterion("job_require not between", value1, value2, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobWorkIsNull() {
            addCriterion("job_work is null");
            return (Criteria) this;
        }

        public Criteria andJobWorkIsNotNull() {
            addCriterion("job_work is not null");
            return (Criteria) this;
        }

        public Criteria andJobWorkEqualTo(String value) {
            addCriterion("job_work =", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotEqualTo(String value) {
            addCriterion("job_work <>", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkGreaterThan(String value) {
            addCriterion("job_work >", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkGreaterThanOrEqualTo(String value) {
            addCriterion("job_work >=", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLessThan(String value) {
            addCriterion("job_work <", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLessThanOrEqualTo(String value) {
            addCriterion("job_work <=", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLike(String value) {
            addCriterion("job_work like", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotLike(String value) {
            addCriterion("job_work not like", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkIn(List<String> values) {
            addCriterion("job_work in", values, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotIn(List<String> values) {
            addCriterion("job_work not in", values, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkBetween(String value1, String value2) {
            addCriterion("job_work between", value1, value2, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotBetween(String value1, String value2) {
            addCriterion("job_work not between", value1, value2, "jobWork");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIsNull() {
            addCriterion("factor_speciality is null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIsNotNull() {
            addCriterion("factor_speciality is not null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityEqualTo(String value) {
            addCriterion("factor_speciality =", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotEqualTo(String value) {
            addCriterion("factor_speciality <>", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityGreaterThan(String value) {
            addCriterion("factor_speciality >", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityGreaterThanOrEqualTo(String value) {
            addCriterion("factor_speciality >=", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLessThan(String value) {
            addCriterion("factor_speciality <", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLessThanOrEqualTo(String value) {
            addCriterion("factor_speciality <=", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLike(String value) {
            addCriterion("factor_speciality like", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotLike(String value) {
            addCriterion("factor_speciality not like", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIn(List<String> values) {
            addCriterion("factor_speciality in", values, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotIn(List<String> values) {
            addCriterion("factor_speciality not in", values, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityBetween(String value1, String value2) {
            addCriterion("factor_speciality between", value1, value2, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotBetween(String value1, String value2) {
            addCriterion("factor_speciality not between", value1, value2, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIsNull() {
            addCriterion("factor_education is null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIsNotNull() {
            addCriterion("factor_education is not null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationEqualTo(String value) {
            addCriterion("factor_education =", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotEqualTo(String value) {
            addCriterion("factor_education <>", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationGreaterThan(String value) {
            addCriterion("factor_education >", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationGreaterThanOrEqualTo(String value) {
            addCriterion("factor_education >=", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLessThan(String value) {
            addCriterion("factor_education <", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLessThanOrEqualTo(String value) {
            addCriterion("factor_education <=", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLike(String value) {
            addCriterion("factor_education like", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotLike(String value) {
            addCriterion("factor_education not like", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIn(List<String> values) {
            addCriterion("factor_education in", values, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotIn(List<String> values) {
            addCriterion("factor_education not in", values, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationBetween(String value1, String value2) {
            addCriterion("factor_education between", value1, value2, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotBetween(String value1, String value2) {
            addCriterion("factor_education not between", value1, value2, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIsNull() {
            addCriterion("factor_gender is null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIsNotNull() {
            addCriterion("factor_gender is not null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderEqualTo(String value) {
            addCriterion("factor_gender =", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotEqualTo(String value) {
            addCriterion("factor_gender <>", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderGreaterThan(String value) {
            addCriterion("factor_gender >", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderGreaterThanOrEqualTo(String value) {
            addCriterion("factor_gender >=", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLessThan(String value) {
            addCriterion("factor_gender <", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLessThanOrEqualTo(String value) {
            addCriterion("factor_gender <=", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLike(String value) {
            addCriterion("factor_gender like", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotLike(String value) {
            addCriterion("factor_gender not like", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIn(List<String> values) {
            addCriterion("factor_gender in", values, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotIn(List<String> values) {
            addCriterion("factor_gender not in", values, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderBetween(String value1, String value2) {
            addCriterion("factor_gender between", value1, value2, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotBetween(String value1, String value2) {
            addCriterion("factor_gender not between", value1, value2, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIsNull() {
            addCriterion("factor_domicile is null");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIsNotNull() {
            addCriterion("factor_domicile is not null");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileEqualTo(String value) {
            addCriterion("factor_domicile =", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotEqualTo(String value) {
            addCriterion("factor_domicile <>", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileGreaterThan(String value) {
            addCriterion("factor_domicile >", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileGreaterThanOrEqualTo(String value) {
            addCriterion("factor_domicile >=", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLessThan(String value) {
            addCriterion("factor_domicile <", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLessThanOrEqualTo(String value) {
            addCriterion("factor_domicile <=", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLike(String value) {
            addCriterion("factor_domicile like", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotLike(String value) {
            addCriterion("factor_domicile not like", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIn(List<String> values) {
            addCriterion("factor_domicile in", values, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotIn(List<String> values) {
            addCriterion("factor_domicile not in", values, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileBetween(String value1, String value2) {
            addCriterion("factor_domicile between", value1, value2, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotBetween(String value1, String value2) {
            addCriterion("factor_domicile not between", value1, value2, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIsNull() {
            addCriterion("factor_age_max is null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIsNotNull() {
            addCriterion("factor_age_max is not null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxEqualTo(Integer value) {
            addCriterion("factor_age_max =", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotEqualTo(Integer value) {
            addCriterion("factor_age_max <>", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxGreaterThan(Integer value) {
            addCriterion("factor_age_max >", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("factor_age_max >=", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxLessThan(Integer value) {
            addCriterion("factor_age_max <", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxLessThanOrEqualTo(Integer value) {
            addCriterion("factor_age_max <=", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIn(List<Integer> values) {
            addCriterion("factor_age_max in", values, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotIn(List<Integer> values) {
            addCriterion("factor_age_max not in", values, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_max between", value1, value2, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_max not between", value1, value2, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIsNull() {
            addCriterion("factor_age_min is null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIsNotNull() {
            addCriterion("factor_age_min is not null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinEqualTo(Integer value) {
            addCriterion("factor_age_min =", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotEqualTo(Integer value) {
            addCriterion("factor_age_min <>", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinGreaterThan(Integer value) {
            addCriterion("factor_age_min >", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("factor_age_min >=", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinLessThan(Integer value) {
            addCriterion("factor_age_min <", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinLessThanOrEqualTo(Integer value) {
            addCriterion("factor_age_min <=", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIn(List<Integer> values) {
            addCriterion("factor_age_min in", values, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotIn(List<Integer> values) {
            addCriterion("factor_age_min not in", values, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_min between", value1, value2, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_min not between", value1, value2, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorDescIsNull() {
            addCriterion("factor_desc is null");
            return (Criteria) this;
        }

        public Criteria andFactorDescIsNotNull() {
            addCriterion("factor_desc is not null");
            return (Criteria) this;
        }

        public Criteria andFactorDescEqualTo(String value) {
            addCriterion("factor_desc =", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotEqualTo(String value) {
            addCriterion("factor_desc <>", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescGreaterThan(String value) {
            addCriterion("factor_desc >", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescGreaterThanOrEqualTo(String value) {
            addCriterion("factor_desc >=", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLessThan(String value) {
            addCriterion("factor_desc <", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLessThanOrEqualTo(String value) {
            addCriterion("factor_desc <=", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLike(String value) {
            addCriterion("factor_desc like", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotLike(String value) {
            addCriterion("factor_desc not like", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescIn(List<String> values) {
            addCriterion("factor_desc in", values, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotIn(List<String> values) {
            addCriterion("factor_desc not in", values, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescBetween(String value1, String value2) {
            addCriterion("factor_desc between", value1, value2, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotBetween(String value1, String value2) {
            addCriterion("factor_desc not between", value1, value2, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNull() {
            addCriterion("add_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNotNull() {
            addCriterion("add_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdEqualTo(String value) {
            addCriterion("add_user_id =", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotEqualTo(String value) {
            addCriterion("add_user_id <>", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThan(String value) {
            addCriterion("add_user_id >", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_id >=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThan(String value) {
            addCriterion("add_user_id <", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_user_id <=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLike(String value) {
            addCriterion("add_user_id like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotLike(String value) {
            addCriterion("add_user_id not like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIn(List<String> values) {
            addCriterion("add_user_id in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotIn(List<String> values) {
            addCriterion("add_user_id not in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdBetween(String value1, String value2) {
            addCriterion("add_user_id between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotBetween(String value1, String value2) {
            addCriterion("add_user_id not between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNull() {
            addCriterion("add_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNotNull() {
            addCriterion("add_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmEqualTo(String value) {
            addCriterion("add_user_nm =", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotEqualTo(String value) {
            addCriterion("add_user_nm <>", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThan(String value) {
            addCriterion("add_user_nm >", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_nm >=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThan(String value) {
            addCriterion("add_user_nm <", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThanOrEqualTo(String value) {
            addCriterion("add_user_nm <=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLike(String value) {
            addCriterion("add_user_nm like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotLike(String value) {
            addCriterion("add_user_nm not like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIn(List<String> values) {
            addCriterion("add_user_nm in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotIn(List<String> values) {
            addCriterion("add_user_nm not in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmBetween(String value1, String value2) {
            addCriterion("add_user_nm between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotBetween(String value1, String value2) {
            addCriterion("add_user_nm not between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("upd_user_id =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("upd_user_id <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("upd_user_id >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_id >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("upd_user_id <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("upd_user_id <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("upd_user_id like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("upd_user_id not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("upd_user_id in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("upd_user_id not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("upd_user_id between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("upd_user_id not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNull() {
            addCriterion("upd_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNotNull() {
            addCriterion("upd_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmEqualTo(String value) {
            addCriterion("upd_user_nm =", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotEqualTo(String value) {
            addCriterion("upd_user_nm <>", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThan(String value) {
            addCriterion("upd_user_nm >", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_nm >=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThan(String value) {
            addCriterion("upd_user_nm <", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThanOrEqualTo(String value) {
            addCriterion("upd_user_nm <=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLike(String value) {
            addCriterion("upd_user_nm like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotLike(String value) {
            addCriterion("upd_user_nm not like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIn(List<String> values) {
            addCriterion("upd_user_nm in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotIn(List<String> values) {
            addCriterion("upd_user_nm not in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmBetween(String value1, String value2) {
            addCriterion("upd_user_nm between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotBetween(String value1, String value2) {
            addCriterion("upd_user_nm not between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNull() {
            addCriterion("upd_terminal_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNotNull() {
            addCriterion("upd_terminal_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpEqualTo(String value) {
            addCriterion("upd_terminal_ip =", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotEqualTo(String value) {
            addCriterion("upd_terminal_ip <>", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThan(String value) {
            addCriterion("upd_terminal_ip >", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip >=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThan(String value) {
            addCriterion("upd_terminal_ip <", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip <=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLike(String value) {
            addCriterion("upd_terminal_ip like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotLike(String value) {
            addCriterion("upd_terminal_ip not like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIn(List<String> values) {
            addCriterion("upd_terminal_ip in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotIn(List<String> values) {
            addCriterion("upd_terminal_ip not in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip not between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_job_details
     * do_not_delete_during_merge 2023-08-08 23:13:18
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}