package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.Criterion;
import java.util.ArrayList;
import java.util.List;

public class JobMustExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-10-11 08:32:41
     */
    protected boolean distinct;

    /**
     * 2023-10-11 08:32:41
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public JobMustExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(String value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(String value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(String value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(String value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(String value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(String value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLike(String value) {
            addCriterion("job_id like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotLike(String value) {
            addCriterion("job_id not like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<String> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<String> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(String value1, String value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(String value1, String value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIsNull() {
            addCriterion("dict_item_id is null");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIsNotNull() {
            addCriterion("dict_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemIdEqualTo(String value) {
            addCriterion("dict_item_id =", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotEqualTo(String value) {
            addCriterion("dict_item_id <>", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdGreaterThan(String value) {
            addCriterion("dict_item_id >", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_id >=", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLessThan(String value) {
            addCriterion("dict_item_id <", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLessThanOrEqualTo(String value) {
            addCriterion("dict_item_id <=", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLike(String value) {
            addCriterion("dict_item_id like", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotLike(String value) {
            addCriterion("dict_item_id not like", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIn(List<String> values) {
            addCriterion("dict_item_id in", values, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotIn(List<String> values) {
            addCriterion("dict_item_id not in", values, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdBetween(String value1, String value2) {
            addCriterion("dict_item_id between", value1, value2, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotBetween(String value1, String value2) {
            addCriterion("dict_item_id not between", value1, value2, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIsNull() {
            addCriterion("notice_id is null");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIsNotNull() {
            addCriterion("notice_id is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeIdEqualTo(String value) {
            addCriterion("notice_id =", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotEqualTo(String value) {
            addCriterion("notice_id <>", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdGreaterThan(String value) {
            addCriterion("notice_id >", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdGreaterThanOrEqualTo(String value) {
            addCriterion("notice_id >=", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdLessThan(String value) {
            addCriterion("notice_id <", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdLessThanOrEqualTo(String value) {
            addCriterion("notice_id <=", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdLike(String value) {
            addCriterion("notice_id like", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotLike(String value) {
            addCriterion("notice_id not like", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIn(List<String> values) {
            addCriterion("notice_id in", values, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotIn(List<String> values) {
            addCriterion("notice_id not in", values, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdBetween(String value1, String value2) {
            addCriterion("notice_id between", value1, value2, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotBetween(String value1, String value2) {
            addCriterion("notice_id not between", value1, value2, "noticeId");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIsNull() {
            addCriterion("dict_item_key is null");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIsNotNull() {
            addCriterion("dict_item_key is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyEqualTo(String value) {
            addCriterion("dict_item_key =", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotEqualTo(String value) {
            addCriterion("dict_item_key <>", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyGreaterThan(String value) {
            addCriterion("dict_item_key >", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_key >=", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLessThan(String value) {
            addCriterion("dict_item_key <", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLessThanOrEqualTo(String value) {
            addCriterion("dict_item_key <=", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLike(String value) {
            addCriterion("dict_item_key like", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotLike(String value) {
            addCriterion("dict_item_key not like", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIn(List<String> values) {
            addCriterion("dict_item_key in", values, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotIn(List<String> values) {
            addCriterion("dict_item_key not in", values, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyBetween(String value1, String value2) {
            addCriterion("dict_item_key between", value1, value2, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotBetween(String value1, String value2) {
            addCriterion("dict_item_key not between", value1, value2, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIsNull() {
            addCriterion("dict_item_value is null");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIsNotNull() {
            addCriterion("dict_item_value is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemValueEqualTo(String value) {
            addCriterion("dict_item_value =", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotEqualTo(String value) {
            addCriterion("dict_item_value <>", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueGreaterThan(String value) {
            addCriterion("dict_item_value >", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_value >=", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLessThan(String value) {
            addCriterion("dict_item_value <", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLessThanOrEqualTo(String value) {
            addCriterion("dict_item_value <=", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLike(String value) {
            addCriterion("dict_item_value like", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotLike(String value) {
            addCriterion("dict_item_value not like", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIn(List<String> values) {
            addCriterion("dict_item_value in", values, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotIn(List<String> values) {
            addCriterion("dict_item_value not in", values, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueBetween(String value1, String value2) {
            addCriterion("dict_item_value between", value1, value2, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotBetween(String value1, String value2) {
            addCriterion("dict_item_value not between", value1, value2, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNull() {
            addCriterion("dict_id is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("dict_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(String value) {
            addCriterion("dict_id =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(String value) {
            addCriterion("dict_id <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(String value) {
            addCriterion("dict_id >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_id >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(String value) {
            addCriterion("dict_id <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(String value) {
            addCriterion("dict_id <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLike(String value) {
            addCriterion("dict_id like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotLike(String value) {
            addCriterion("dict_id not like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<String> values) {
            addCriterion("dict_id in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<String> values) {
            addCriterion("dict_id not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(String value1, String value2) {
            addCriterion("dict_id between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(String value1, String value2) {
            addCriterion("dict_id not between", value1, value2, "dictId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_job_must
     * do_not_delete_during_merge 2023-10-11 08:32:41
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}