package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.Criterion;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserAttributeExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-08-29 22:08:35
     */
    protected boolean distinct;

    /**
     * 2023-08-29 22:08:35
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public UserAttributeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_user_attribute
     * 2023-08-29 22:08:35
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNull() {
            addCriterion("dict_Id is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("dict_Id is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(String value) {
            addCriterion("dict_Id =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(String value) {
            addCriterion("dict_Id <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(String value) {
            addCriterion("dict_Id >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_Id >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(String value) {
            addCriterion("dict_Id <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(String value) {
            addCriterion("dict_Id <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLike(String value) {
            addCriterion("dict_Id like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotLike(String value) {
            addCriterion("dict_Id not like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<String> values) {
            addCriterion("dict_Id in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<String> values) {
            addCriterion("dict_Id not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(String value1, String value2) {
            addCriterion("dict_Id between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(String value1, String value2) {
            addCriterion("dict_Id not between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIsNull() {
            addCriterion("dict_item_id is null");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIsNotNull() {
            addCriterion("dict_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemIdEqualTo(String value) {
            addCriterion("dict_item_id =", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotEqualTo(String value) {
            addCriterion("dict_item_id <>", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdGreaterThan(String value) {
            addCriterion("dict_item_id >", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_id >=", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLessThan(String value) {
            addCriterion("dict_item_id <", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLessThanOrEqualTo(String value) {
            addCriterion("dict_item_id <=", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdLike(String value) {
            addCriterion("dict_item_id like", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotLike(String value) {
            addCriterion("dict_item_id not like", value, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdIn(List<String> values) {
            addCriterion("dict_item_id in", values, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotIn(List<String> values) {
            addCriterion("dict_item_id not in", values, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdBetween(String value1, String value2) {
            addCriterion("dict_item_id between", value1, value2, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemIdNotBetween(String value1, String value2) {
            addCriterion("dict_item_id not between", value1, value2, "dictItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIsNull() {
            addCriterion("dict_item_key is null");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIsNotNull() {
            addCriterion("dict_item_key is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyEqualTo(String value) {
            addCriterion("dict_item_key =", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotEqualTo(String value) {
            addCriterion("dict_item_key <>", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyGreaterThan(String value) {
            addCriterion("dict_item_key >", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_key >=", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLessThan(String value) {
            addCriterion("dict_item_key <", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLessThanOrEqualTo(String value) {
            addCriterion("dict_item_key <=", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyLike(String value) {
            addCriterion("dict_item_key like", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotLike(String value) {
            addCriterion("dict_item_key not like", value, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyIn(List<String> values) {
            addCriterion("dict_item_key in", values, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotIn(List<String> values) {
            addCriterion("dict_item_key not in", values, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyBetween(String value1, String value2) {
            addCriterion("dict_item_key between", value1, value2, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andDictItemKeyNotBetween(String value1, String value2) {
            addCriterion("dict_item_key not between", value1, value2, "dictItemKey");
            return (Criteria) this;
        }

        public Criteria andParentItemIdIsNull() {
            addCriterion("parent_item_id is null");
            return (Criteria) this;
        }

        public Criteria andParentItemIdIsNotNull() {
            addCriterion("parent_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentItemIdEqualTo(String value) {
            addCriterion("parent_item_id =", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdNotEqualTo(String value) {
            addCriterion("parent_item_id <>", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdGreaterThan(String value) {
            addCriterion("parent_item_id >", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_item_id >=", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdLessThan(String value) {
            addCriterion("parent_item_id <", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdLessThanOrEqualTo(String value) {
            addCriterion("parent_item_id <=", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdLike(String value) {
            addCriterion("parent_item_id like", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdNotLike(String value) {
            addCriterion("parent_item_id not like", value, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdIn(List<String> values) {
            addCriterion("parent_item_id in", values, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdNotIn(List<String> values) {
            addCriterion("parent_item_id not in", values, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdBetween(String value1, String value2) {
            addCriterion("parent_item_id between", value1, value2, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andParentItemIdNotBetween(String value1, String value2) {
            addCriterion("parent_item_id not between", value1, value2, "parentItemId");
            return (Criteria) this;
        }

        public Criteria andDictItemValIsNull() {
            addCriterion("dict_item_val is null");
            return (Criteria) this;
        }

        public Criteria andDictItemValIsNotNull() {
            addCriterion("dict_item_val is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemValEqualTo(String value) {
            addCriterion("dict_item_val =", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValNotEqualTo(String value) {
            addCriterion("dict_item_val <>", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValGreaterThan(String value) {
            addCriterion("dict_item_val >", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValGreaterThanOrEqualTo(String value) {
            addCriterion("dict_item_val >=", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValLessThan(String value) {
            addCriterion("dict_item_val <", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValLessThanOrEqualTo(String value) {
            addCriterion("dict_item_val <=", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValLike(String value) {
            addCriterion("dict_item_val like", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValNotLike(String value) {
            addCriterion("dict_item_val not like", value, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValIn(List<String> values) {
            addCriterion("dict_item_val in", values, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValNotIn(List<String> values) {
            addCriterion("dict_item_val not in", values, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValBetween(String value1, String value2) {
            addCriterion("dict_item_val between", value1, value2, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andDictItemValNotBetween(String value1, String value2) {
            addCriterion("dict_item_val not between", value1, value2, "dictItemVal");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNull() {
            addCriterion("add_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNotNull() {
            addCriterion("add_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdEqualTo(String value) {
            addCriterion("add_user_id =", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotEqualTo(String value) {
            addCriterion("add_user_id <>", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThan(String value) {
            addCriterion("add_user_id >", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_id >=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThan(String value) {
            addCriterion("add_user_id <", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_user_id <=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLike(String value) {
            addCriterion("add_user_id like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotLike(String value) {
            addCriterion("add_user_id not like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIn(List<String> values) {
            addCriterion("add_user_id in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotIn(List<String> values) {
            addCriterion("add_user_id not in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdBetween(String value1, String value2) {
            addCriterion("add_user_id between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotBetween(String value1, String value2) {
            addCriterion("add_user_id not between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNull() {
            addCriterion("add_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNotNull() {
            addCriterion("add_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmEqualTo(String value) {
            addCriterion("add_user_nm =", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotEqualTo(String value) {
            addCriterion("add_user_nm <>", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThan(String value) {
            addCriterion("add_user_nm >", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_nm >=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThan(String value) {
            addCriterion("add_user_nm <", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThanOrEqualTo(String value) {
            addCriterion("add_user_nm <=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLike(String value) {
            addCriterion("add_user_nm like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotLike(String value) {
            addCriterion("add_user_nm not like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIn(List<String> values) {
            addCriterion("add_user_nm in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotIn(List<String> values) {
            addCriterion("add_user_nm not in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmBetween(String value1, String value2) {
            addCriterion("add_user_nm between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotBetween(String value1, String value2) {
            addCriterion("add_user_nm not between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("upd_user_id =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("upd_user_id <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("upd_user_id >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_id >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("upd_user_id <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("upd_user_id <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("upd_user_id like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("upd_user_id not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("upd_user_id in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("upd_user_id not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("upd_user_id between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("upd_user_id not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNull() {
            addCriterion("upd_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNotNull() {
            addCriterion("upd_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmEqualTo(String value) {
            addCriterion("upd_user_nm =", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotEqualTo(String value) {
            addCriterion("upd_user_nm <>", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThan(String value) {
            addCriterion("upd_user_nm >", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_nm >=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThan(String value) {
            addCriterion("upd_user_nm <", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThanOrEqualTo(String value) {
            addCriterion("upd_user_nm <=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLike(String value) {
            addCriterion("upd_user_nm like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotLike(String value) {
            addCriterion("upd_user_nm not like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIn(List<String> values) {
            addCriterion("upd_user_nm in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotIn(List<String> values) {
            addCriterion("upd_user_nm not in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmBetween(String value1, String value2) {
            addCriterion("upd_user_nm between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotBetween(String value1, String value2) {
            addCriterion("upd_user_nm not between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNull() {
            addCriterion("upd_terminal_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNotNull() {
            addCriterion("upd_terminal_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpEqualTo(String value) {
            addCriterion("upd_terminal_ip =", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotEqualTo(String value) {
            addCriterion("upd_terminal_ip <>", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThan(String value) {
            addCriterion("upd_terminal_ip >", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip >=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThan(String value) {
            addCriterion("upd_terminal_ip <", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip <=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLike(String value) {
            addCriterion("upd_terminal_ip like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotLike(String value) {
            addCriterion("upd_terminal_ip not like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIn(List<String> values) {
            addCriterion("upd_terminal_ip in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotIn(List<String> values) {
            addCriterion("upd_terminal_ip not in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip not between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gks_user_attribute
     * do_not_delete_during_merge 2023-08-29 22:08:35
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}