package com.kiun.functionary.dao.gks.entity;

import com.kiun.functionary.base.Criterion;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VJobInfoExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-09-12 23:45:53
     */
    protected boolean distinct;

    /**
     * 2023-09-12 23:45:53
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public VJobInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_gks_job_info
     * 2023-09-12 23:45:53
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIsNull() {
            addCriterion("job_notice is null");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIsNotNull() {
            addCriterion("job_notice is not null");
            return (Criteria) this;
        }

        public Criteria andJobNoticeEqualTo(String value) {
            addCriterion("job_notice =", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotEqualTo(String value) {
            addCriterion("job_notice <>", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeGreaterThan(String value) {
            addCriterion("job_notice >", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("job_notice >=", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLessThan(String value) {
            addCriterion("job_notice <", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLessThanOrEqualTo(String value) {
            addCriterion("job_notice <=", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeLike(String value) {
            addCriterion("job_notice like", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotLike(String value) {
            addCriterion("job_notice not like", value, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeIn(List<String> values) {
            addCriterion("job_notice in", values, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotIn(List<String> values) {
            addCriterion("job_notice not in", values, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeBetween(String value1, String value2) {
            addCriterion("job_notice between", value1, value2, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNoticeNotBetween(String value1, String value2) {
            addCriterion("job_notice not between", value1, value2, "jobNotice");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobCountIsNull() {
            addCriterion("job_count is null");
            return (Criteria) this;
        }

        public Criteria andJobCountIsNotNull() {
            addCriterion("job_count is not null");
            return (Criteria) this;
        }

        public Criteria andJobCountEqualTo(Integer value) {
            addCriterion("job_count =", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotEqualTo(Integer value) {
            addCriterion("job_count <>", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountGreaterThan(Integer value) {
            addCriterion("job_count >", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_count >=", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountLessThan(Integer value) {
            addCriterion("job_count <", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountLessThanOrEqualTo(Integer value) {
            addCriterion("job_count <=", value, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountIn(List<Integer> values) {
            addCriterion("job_count in", values, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotIn(List<Integer> values) {
            addCriterion("job_count not in", values, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountBetween(Integer value1, Integer value2) {
            addCriterion("job_count between", value1, value2, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobCountNotBetween(Integer value1, Integer value2) {
            addCriterion("job_count not between", value1, value2, "jobCount");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNull() {
            addCriterion("job_salary is null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNotNull() {
            addCriterion("job_salary is not null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryEqualTo(BigDecimal value) {
            addCriterion("job_salary =", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotEqualTo(BigDecimal value) {
            addCriterion("job_salary <>", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThan(BigDecimal value) {
            addCriterion("job_salary >", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("job_salary >=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThan(BigDecimal value) {
            addCriterion("job_salary <", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("job_salary <=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIn(List<BigDecimal> values) {
            addCriterion("job_salary in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotIn(List<BigDecimal> values) {
            addCriterion("job_salary not in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_salary between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_salary not between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobRequireIsNull() {
            addCriterion("job_require is null");
            return (Criteria) this;
        }

        public Criteria andJobRequireIsNotNull() {
            addCriterion("job_require is not null");
            return (Criteria) this;
        }

        public Criteria andJobRequireEqualTo(String value) {
            addCriterion("job_require =", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotEqualTo(String value) {
            addCriterion("job_require <>", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireGreaterThan(String value) {
            addCriterion("job_require >", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireGreaterThanOrEqualTo(String value) {
            addCriterion("job_require >=", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLessThan(String value) {
            addCriterion("job_require <", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLessThanOrEqualTo(String value) {
            addCriterion("job_require <=", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireLike(String value) {
            addCriterion("job_require like", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotLike(String value) {
            addCriterion("job_require not like", value, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireIn(List<String> values) {
            addCriterion("job_require in", values, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotIn(List<String> values) {
            addCriterion("job_require not in", values, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireBetween(String value1, String value2) {
            addCriterion("job_require between", value1, value2, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobRequireNotBetween(String value1, String value2) {
            addCriterion("job_require not between", value1, value2, "jobRequire");
            return (Criteria) this;
        }

        public Criteria andJobWorkIsNull() {
            addCriterion("job_work is null");
            return (Criteria) this;
        }

        public Criteria andJobWorkIsNotNull() {
            addCriterion("job_work is not null");
            return (Criteria) this;
        }

        public Criteria andJobWorkEqualTo(String value) {
            addCriterion("job_work =", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotEqualTo(String value) {
            addCriterion("job_work <>", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkGreaterThan(String value) {
            addCriterion("job_work >", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkGreaterThanOrEqualTo(String value) {
            addCriterion("job_work >=", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLessThan(String value) {
            addCriterion("job_work <", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLessThanOrEqualTo(String value) {
            addCriterion("job_work <=", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkLike(String value) {
            addCriterion("job_work like", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotLike(String value) {
            addCriterion("job_work not like", value, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkIn(List<String> values) {
            addCriterion("job_work in", values, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotIn(List<String> values) {
            addCriterion("job_work not in", values, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkBetween(String value1, String value2) {
            addCriterion("job_work between", value1, value2, "jobWork");
            return (Criteria) this;
        }

        public Criteria andJobWorkNotBetween(String value1, String value2) {
            addCriterion("job_work not between", value1, value2, "jobWork");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIsNull() {
            addCriterion("factor_speciality is null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIsNotNull() {
            addCriterion("factor_speciality is not null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityEqualTo(String value) {
            addCriterion("factor_speciality =", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotEqualTo(String value) {
            addCriterion("factor_speciality <>", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityGreaterThan(String value) {
            addCriterion("factor_speciality >", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityGreaterThanOrEqualTo(String value) {
            addCriterion("factor_speciality >=", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLessThan(String value) {
            addCriterion("factor_speciality <", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLessThanOrEqualTo(String value) {
            addCriterion("factor_speciality <=", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityLike(String value) {
            addCriterion("factor_speciality like", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotLike(String value) {
            addCriterion("factor_speciality not like", value, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityIn(List<String> values) {
            addCriterion("factor_speciality in", values, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotIn(List<String> values) {
            addCriterion("factor_speciality not in", values, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityBetween(String value1, String value2) {
            addCriterion("factor_speciality between", value1, value2, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNotBetween(String value1, String value2) {
            addCriterion("factor_speciality not between", value1, value2, "factorSpeciality");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameIsNull() {
            addCriterion("factor_speciality_name is null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameIsNotNull() {
            addCriterion("factor_speciality_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameEqualTo(String value) {
            addCriterion("factor_speciality_name =", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameNotEqualTo(String value) {
            addCriterion("factor_speciality_name <>", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameGreaterThan(String value) {
            addCriterion("factor_speciality_name >", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameGreaterThanOrEqualTo(String value) {
            addCriterion("factor_speciality_name >=", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameLessThan(String value) {
            addCriterion("factor_speciality_name <", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameLessThanOrEqualTo(String value) {
            addCriterion("factor_speciality_name <=", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameLike(String value) {
            addCriterion("factor_speciality_name like", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameNotLike(String value) {
            addCriterion("factor_speciality_name not like", value, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameIn(List<String> values) {
            addCriterion("factor_speciality_name in", values, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameNotIn(List<String> values) {
            addCriterion("factor_speciality_name not in", values, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameBetween(String value1, String value2) {
            addCriterion("factor_speciality_name between", value1, value2, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorSpecialityNameNotBetween(String value1, String value2) {
            addCriterion("factor_speciality_name not between", value1, value2, "factorSpecialityName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIsNull() {
            addCriterion("factor_education is null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIsNotNull() {
            addCriterion("factor_education is not null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationEqualTo(String value) {
            addCriterion("factor_education =", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotEqualTo(String value) {
            addCriterion("factor_education <>", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationGreaterThan(String value) {
            addCriterion("factor_education >", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationGreaterThanOrEqualTo(String value) {
            addCriterion("factor_education >=", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLessThan(String value) {
            addCriterion("factor_education <", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLessThanOrEqualTo(String value) {
            addCriterion("factor_education <=", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationLike(String value) {
            addCriterion("factor_education like", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotLike(String value) {
            addCriterion("factor_education not like", value, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationIn(List<String> values) {
            addCriterion("factor_education in", values, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotIn(List<String> values) {
            addCriterion("factor_education not in", values, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationBetween(String value1, String value2) {
            addCriterion("factor_education between", value1, value2, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNotBetween(String value1, String value2) {
            addCriterion("factor_education not between", value1, value2, "factorEducation");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameIsNull() {
            addCriterion("factor_education_name is null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameIsNotNull() {
            addCriterion("factor_education_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameEqualTo(String value) {
            addCriterion("factor_education_name =", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameNotEqualTo(String value) {
            addCriterion("factor_education_name <>", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameGreaterThan(String value) {
            addCriterion("factor_education_name >", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameGreaterThanOrEqualTo(String value) {
            addCriterion("factor_education_name >=", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameLessThan(String value) {
            addCriterion("factor_education_name <", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameLessThanOrEqualTo(String value) {
            addCriterion("factor_education_name <=", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameLike(String value) {
            addCriterion("factor_education_name like", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameNotLike(String value) {
            addCriterion("factor_education_name not like", value, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameIn(List<String> values) {
            addCriterion("factor_education_name in", values, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameNotIn(List<String> values) {
            addCriterion("factor_education_name not in", values, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameBetween(String value1, String value2) {
            addCriterion("factor_education_name between", value1, value2, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorEducationNameNotBetween(String value1, String value2) {
            addCriterion("factor_education_name not between", value1, value2, "factorEducationName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIsNull() {
            addCriterion("factor_gender is null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIsNotNull() {
            addCriterion("factor_gender is not null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderEqualTo(String value) {
            addCriterion("factor_gender =", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotEqualTo(String value) {
            addCriterion("factor_gender <>", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderGreaterThan(String value) {
            addCriterion("factor_gender >", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderGreaterThanOrEqualTo(String value) {
            addCriterion("factor_gender >=", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLessThan(String value) {
            addCriterion("factor_gender <", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLessThanOrEqualTo(String value) {
            addCriterion("factor_gender <=", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderLike(String value) {
            addCriterion("factor_gender like", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotLike(String value) {
            addCriterion("factor_gender not like", value, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderIn(List<String> values) {
            addCriterion("factor_gender in", values, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotIn(List<String> values) {
            addCriterion("factor_gender not in", values, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderBetween(String value1, String value2) {
            addCriterion("factor_gender between", value1, value2, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNotBetween(String value1, String value2) {
            addCriterion("factor_gender not between", value1, value2, "factorGender");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameIsNull() {
            addCriterion("factor_gender_name is null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameIsNotNull() {
            addCriterion("factor_gender_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameEqualTo(String value) {
            addCriterion("factor_gender_name =", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameNotEqualTo(String value) {
            addCriterion("factor_gender_name <>", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameGreaterThan(String value) {
            addCriterion("factor_gender_name >", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("factor_gender_name >=", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameLessThan(String value) {
            addCriterion("factor_gender_name <", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameLessThanOrEqualTo(String value) {
            addCriterion("factor_gender_name <=", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameLike(String value) {
            addCriterion("factor_gender_name like", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameNotLike(String value) {
            addCriterion("factor_gender_name not like", value, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameIn(List<String> values) {
            addCriterion("factor_gender_name in", values, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameNotIn(List<String> values) {
            addCriterion("factor_gender_name not in", values, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameBetween(String value1, String value2) {
            addCriterion("factor_gender_name between", value1, value2, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorGenderNameNotBetween(String value1, String value2) {
            addCriterion("factor_gender_name not between", value1, value2, "factorGenderName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoIsNull() {
            addCriterion("factor_undergo is null");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoIsNotNull() {
            addCriterion("factor_undergo is not null");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoEqualTo(String value) {
            addCriterion("factor_undergo =", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNotEqualTo(String value) {
            addCriterion("factor_undergo <>", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoGreaterThan(String value) {
            addCriterion("factor_undergo >", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoGreaterThanOrEqualTo(String value) {
            addCriterion("factor_undergo >=", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoLessThan(String value) {
            addCriterion("factor_undergo <", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoLessThanOrEqualTo(String value) {
            addCriterion("factor_undergo <=", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoLike(String value) {
            addCriterion("factor_undergo like", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNotLike(String value) {
            addCriterion("factor_undergo not like", value, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoIn(List<String> values) {
            addCriterion("factor_undergo in", values, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNotIn(List<String> values) {
            addCriterion("factor_undergo not in", values, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoBetween(String value1, String value2) {
            addCriterion("factor_undergo between", value1, value2, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNotBetween(String value1, String value2) {
            addCriterion("factor_undergo not between", value1, value2, "factorUndergo");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameIsNull() {
            addCriterion("factor_undergo_name is null");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameIsNotNull() {
            addCriterion("factor_undergo_name is not null");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameEqualTo(String value) {
            addCriterion("factor_undergo_name =", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameNotEqualTo(String value) {
            addCriterion("factor_undergo_name <>", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameGreaterThan(String value) {
            addCriterion("factor_undergo_name >", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameGreaterThanOrEqualTo(String value) {
            addCriterion("factor_undergo_name >=", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameLessThan(String value) {
            addCriterion("factor_undergo_name <", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameLessThanOrEqualTo(String value) {
            addCriterion("factor_undergo_name <=", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameLike(String value) {
            addCriterion("factor_undergo_name like", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameNotLike(String value) {
            addCriterion("factor_undergo_name not like", value, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameIn(List<String> values) {
            addCriterion("factor_undergo_name in", values, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameNotIn(List<String> values) {
            addCriterion("factor_undergo_name not in", values, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameBetween(String value1, String value2) {
            addCriterion("factor_undergo_name between", value1, value2, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorUndergoNameNotBetween(String value1, String value2) {
            addCriterion("factor_undergo_name not between", value1, value2, "factorUndergoName");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIsNull() {
            addCriterion("factor_domicile is null");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIsNotNull() {
            addCriterion("factor_domicile is not null");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileEqualTo(String value) {
            addCriterion("factor_domicile =", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotEqualTo(String value) {
            addCriterion("factor_domicile <>", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileGreaterThan(String value) {
            addCriterion("factor_domicile >", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileGreaterThanOrEqualTo(String value) {
            addCriterion("factor_domicile >=", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLessThan(String value) {
            addCriterion("factor_domicile <", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLessThanOrEqualTo(String value) {
            addCriterion("factor_domicile <=", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileLike(String value) {
            addCriterion("factor_domicile like", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotLike(String value) {
            addCriterion("factor_domicile not like", value, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileIn(List<String> values) {
            addCriterion("factor_domicile in", values, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotIn(List<String> values) {
            addCriterion("factor_domicile not in", values, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileBetween(String value1, String value2) {
            addCriterion("factor_domicile between", value1, value2, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorDomicileNotBetween(String value1, String value2) {
            addCriterion("factor_domicile not between", value1, value2, "factorDomicile");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIsNull() {
            addCriterion("factor_age_max is null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIsNotNull() {
            addCriterion("factor_age_max is not null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxEqualTo(Integer value) {
            addCriterion("factor_age_max =", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotEqualTo(Integer value) {
            addCriterion("factor_age_max <>", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxGreaterThan(Integer value) {
            addCriterion("factor_age_max >", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("factor_age_max >=", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxLessThan(Integer value) {
            addCriterion("factor_age_max <", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxLessThanOrEqualTo(Integer value) {
            addCriterion("factor_age_max <=", value, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxIn(List<Integer> values) {
            addCriterion("factor_age_max in", values, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotIn(List<Integer> values) {
            addCriterion("factor_age_max not in", values, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_max between", value1, value2, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_max not between", value1, value2, "factorAgeMax");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIsNull() {
            addCriterion("factor_age_min is null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIsNotNull() {
            addCriterion("factor_age_min is not null");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinEqualTo(Integer value) {
            addCriterion("factor_age_min =", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotEqualTo(Integer value) {
            addCriterion("factor_age_min <>", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinGreaterThan(Integer value) {
            addCriterion("factor_age_min >", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("factor_age_min >=", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinLessThan(Integer value) {
            addCriterion("factor_age_min <", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinLessThanOrEqualTo(Integer value) {
            addCriterion("factor_age_min <=", value, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinIn(List<Integer> values) {
            addCriterion("factor_age_min in", values, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotIn(List<Integer> values) {
            addCriterion("factor_age_min not in", values, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_min between", value1, value2, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorAgeMinNotBetween(Integer value1, Integer value2) {
            addCriterion("factor_age_min not between", value1, value2, "factorAgeMin");
            return (Criteria) this;
        }

        public Criteria andFactorDescIsNull() {
            addCriterion("factor_desc is null");
            return (Criteria) this;
        }

        public Criteria andFactorDescIsNotNull() {
            addCriterion("factor_desc is not null");
            return (Criteria) this;
        }

        public Criteria andFactorDescEqualTo(String value) {
            addCriterion("factor_desc =", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotEqualTo(String value) {
            addCriterion("factor_desc <>", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescGreaterThan(String value) {
            addCriterion("factor_desc >", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescGreaterThanOrEqualTo(String value) {
            addCriterion("factor_desc >=", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLessThan(String value) {
            addCriterion("factor_desc <", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLessThanOrEqualTo(String value) {
            addCriterion("factor_desc <=", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescLike(String value) {
            addCriterion("factor_desc like", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotLike(String value) {
            addCriterion("factor_desc not like", value, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescIn(List<String> values) {
            addCriterion("factor_desc in", values, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotIn(List<String> values) {
            addCriterion("factor_desc not in", values, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescBetween(String value1, String value2) {
            addCriterion("factor_desc between", value1, value2, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andFactorDescNotBetween(String value1, String value2) {
            addCriterion("factor_desc not between", value1, value2, "factorDesc");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNull() {
            addCriterion("add_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNotNull() {
            addCriterion("add_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdEqualTo(String value) {
            addCriterion("add_user_id =", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotEqualTo(String value) {
            addCriterion("add_user_id <>", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThan(String value) {
            addCriterion("add_user_id >", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_id >=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThan(String value) {
            addCriterion("add_user_id <", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_user_id <=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLike(String value) {
            addCriterion("add_user_id like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotLike(String value) {
            addCriterion("add_user_id not like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIn(List<String> values) {
            addCriterion("add_user_id in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotIn(List<String> values) {
            addCriterion("add_user_id not in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdBetween(String value1, String value2) {
            addCriterion("add_user_id between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotBetween(String value1, String value2) {
            addCriterion("add_user_id not between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("upd_user_id =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("upd_user_id <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("upd_user_id >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_id >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("upd_user_id <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("upd_user_id <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("upd_user_id like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("upd_user_id not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("upd_user_id in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("upd_user_id not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("upd_user_id between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("upd_user_id not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNull() {
            addCriterion("upd_terminal_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNotNull() {
            addCriterion("upd_terminal_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpEqualTo(String value) {
            addCriterion("upd_terminal_ip =", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotEqualTo(String value) {
            addCriterion("upd_terminal_ip <>", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThan(String value) {
            addCriterion("upd_terminal_ip >", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip >=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThan(String value) {
            addCriterion("upd_terminal_ip <", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip <=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLike(String value) {
            addCriterion("upd_terminal_ip like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotLike(String value) {
            addCriterion("upd_terminal_ip not like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIn(List<String> values) {
            addCriterion("upd_terminal_ip in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotIn(List<String> values) {
            addCriterion("upd_terminal_ip not in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip not between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Long value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Long value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Long value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Long value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Long value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Long value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Long> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Long> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Long value1, Long value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Long value1, Long value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountIsNull() {
            addCriterion("notice_job_count is null");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountIsNotNull() {
            addCriterion("notice_job_count is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountEqualTo(BigDecimal value) {
            addCriterion("notice_job_count =", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountNotEqualTo(BigDecimal value) {
            addCriterion("notice_job_count <>", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountGreaterThan(BigDecimal value) {
            addCriterion("notice_job_count >", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("notice_job_count >=", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountLessThan(BigDecimal value) {
            addCriterion("notice_job_count <", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("notice_job_count <=", value, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountIn(List<BigDecimal> values) {
            addCriterion("notice_job_count in", values, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountNotIn(List<BigDecimal> values) {
            addCriterion("notice_job_count not in", values, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("notice_job_count between", value1, value2, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andNoticeJobCountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("notice_job_count not between", value1, value2, "noticeJobCount");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("publish_time =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("publish_time <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("publish_time >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_time >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("publish_time <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("publish_time <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("publish_time in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("publish_time not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("publish_time between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("publish_time not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andOrganNameIsNull() {
            addCriterion("organ_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganNameIsNotNull() {
            addCriterion("organ_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganNameEqualTo(String value) {
            addCriterion("organ_name =", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameNotEqualTo(String value) {
            addCriterion("organ_name <>", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameGreaterThan(String value) {
            addCriterion("organ_name >", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameGreaterThanOrEqualTo(String value) {
            addCriterion("organ_name >=", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameLessThan(String value) {
            addCriterion("organ_name <", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameLessThanOrEqualTo(String value) {
            addCriterion("organ_name <=", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameLike(String value) {
            addCriterion("organ_name like", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameNotLike(String value) {
            addCriterion("organ_name not like", value, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameIn(List<String> values) {
            addCriterion("organ_name in", values, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameNotIn(List<String> values) {
            addCriterion("organ_name not in", values, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameBetween(String value1, String value2) {
            addCriterion("organ_name between", value1, value2, "organName");
            return (Criteria) this;
        }

        public Criteria andOrganNameNotBetween(String value1, String value2) {
            addCriterion("organ_name not between", value1, value2, "organName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameIsNull() {
            addCriterion("parent_organ_name is null");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameIsNotNull() {
            addCriterion("parent_organ_name is not null");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameEqualTo(String value) {
            addCriterion("parent_organ_name =", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameNotEqualTo(String value) {
            addCriterion("parent_organ_name <>", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameGreaterThan(String value) {
            addCriterion("parent_organ_name >", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameGreaterThanOrEqualTo(String value) {
            addCriterion("parent_organ_name >=", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameLessThan(String value) {
            addCriterion("parent_organ_name <", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameLessThanOrEqualTo(String value) {
            addCriterion("parent_organ_name <=", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameLike(String value) {
            addCriterion("parent_organ_name like", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameNotLike(String value) {
            addCriterion("parent_organ_name not like", value, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameIn(List<String> values) {
            addCriterion("parent_organ_name in", values, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameNotIn(List<String> values) {
            addCriterion("parent_organ_name not in", values, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameBetween(String value1, String value2) {
            addCriterion("parent_organ_name between", value1, value2, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andParentOrganNameNotBetween(String value1, String value2) {
            addCriterion("parent_organ_name not between", value1, value2, "parentOrganName");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNull() {
            addCriterion("region_name is null");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNotNull() {
            addCriterion("region_name is not null");
            return (Criteria) this;
        }

        public Criteria andRegionNameEqualTo(String value) {
            addCriterion("region_name =", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotEqualTo(String value) {
            addCriterion("region_name <>", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThan(String value) {
            addCriterion("region_name >", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("region_name >=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThan(String value) {
            addCriterion("region_name <", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThanOrEqualTo(String value) {
            addCriterion("region_name <=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLike(String value) {
            addCriterion("region_name like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotLike(String value) {
            addCriterion("region_name not like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIn(List<String> values) {
            addCriterion("region_name in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotIn(List<String> values) {
            addCriterion("region_name not in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameBetween(String value1, String value2) {
            addCriterion("region_name between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotBetween(String value1, String value2) {
            addCriterion("region_name not between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameIsNull() {
            addCriterion("organ_type_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameIsNotNull() {
            addCriterion("organ_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameEqualTo(String value) {
            addCriterion("organ_type_name =", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameNotEqualTo(String value) {
            addCriterion("organ_type_name <>", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameGreaterThan(String value) {
            addCriterion("organ_type_name >", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("organ_type_name >=", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameLessThan(String value) {
            addCriterion("organ_type_name <", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameLessThanOrEqualTo(String value) {
            addCriterion("organ_type_name <=", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameLike(String value) {
            addCriterion("organ_type_name like", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameNotLike(String value) {
            addCriterion("organ_type_name not like", value, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameIn(List<String> values) {
            addCriterion("organ_type_name in", values, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameNotIn(List<String> values) {
            addCriterion("organ_type_name not in", values, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameBetween(String value1, String value2) {
            addCriterion("organ_type_name between", value1, value2, "organTypeName");
            return (Criteria) this;
        }

        public Criteria andOrganTypeNameNotBetween(String value1, String value2) {
            addCriterion("organ_type_name not between", value1, value2, "organTypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_gks_job_info
     * do_not_delete_during_merge 2023-09-12 23:45:53
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}