package com.kiun.functionary.dao.lz;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.lz.entity.BettingPay;
import com.kiun.functionary.dao.lz.entity.BettingPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BettingPayMapper extends com.kiun.functionary.base.BaseExampleMapper<BettingPayExample, BettingPay> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_pay
     * 2024-05-26 11:50:48
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_pay
     * 2024-05-26 11:50:48
     */
    BettingPay selectByPrimaryKey(String id);

    List<BettingPay> selectById(String id);

    List<BettingPay> selectByBettingId(String bettingId);

    List<BettingPay> selectByUserId(String userId);

    List<BettingPay> selectByTransactionId(String transactionId);

    List<BettingPay> selectByAmount(java.math.BigDecimal amount);

    List<BettingPay> selectByCreateTime(java.util.Date createTime);

    List<BettingPay> selectByPayTime(java.util.Date payTime);
}