package com.kiun.functionary.dao.lz;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.lz.entity.BettingHead;
import com.kiun.functionary.dao.lz.entity.BettingHeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BettingHeadMapper extends com.kiun.functionary.base.BaseExampleMapper<BettingHeadExample, BettingHead> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    BettingHead selectByPrimaryKey(String id);

    List<BettingHead> selectById(String id);

    List<BettingHead> selectByUserId(String userId);

    List<BettingHead> selectByBettingCount(Integer bettingCount);

    List<BettingHead> selectByBettingAmount(java.math.BigDecimal bettingAmount);

    List<BettingHead> selectByBettingTime(java.util.Date bettingTime);

    List<BettingHead> selectByBettingType(String bettingType);

    List<BettingHead> selectByState(String state);
}