package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysDictItem;
import com.kiun.functionary.dao.sys.entity.SysDictItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictItemMapper extends com.kiun.functionary.base.BaseExampleMapper<SysDictItemExample, SysDictItem> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     * 2023-07-26 21:14:35
     */
    int deleteByPrimaryKey(@Param("dictId") String dictId, @Param("itemKey") String itemKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_item
     * 2023-07-26 21:14:35
     */
    SysDictItem selectByPrimaryKey(@Param("dictId") String dictId, @Param("itemKey") String itemKey);

    List<SysDictItem> selectByDictId(String dictId);

    List<SysDictItem> selectByItemKey(String itemKey);

    List<SysDictItem> selectById(String id);

    List<SysDictItem> selectByDictName(String dictName);

    List<SysDictItem> selectByParentId(String parentId);

    List<SysDictItem> selectByItemVal(String itemVal);

    List<SysDictItem> selectByItemOrder(Integer itemOrder);

    List<SysDictItem> selectByAddUserId(String addUserId);

    List<SysDictItem> selectByAddUserNm(String addUserNm);

    List<SysDictItem> selectByAddTime(java.util.Date addTime);

    List<SysDictItem> selectByUpdUserId(String updUserId);

    List<SysDictItem> selectByUpdUserNm(String updUserNm);

    List<SysDictItem> selectByUpdTime(java.util.Date updTime);

    List<SysDictItem> selectByUpdTerminalIp(String updTerminalIp);
}