package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysDict;
import com.kiun.functionary.dao.sys.entity.SysDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictMapper extends com.kiun.functionary.base.BaseExampleMapper<SysDictExample, SysDict> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-26 21:14:35
     */
    int deleteByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-26 21:14:35
     */
    SysDict selectByPrimaryKey(String dictId);

    List<SysDict> selectByDictId(String dictId);

    List<SysDict> selectByDictName(String dictName);

    List<SysDict> selectByGroupDict(String groupDict);

    List<SysDict> selectByAddUserId(String addUserId);

    List<SysDict> selectByAddUserNm(String addUserNm);

    List<SysDict> selectByAddTime(java.util.Date addTime);

    List<SysDict> selectByUpdUserId(String updUserId);

    List<SysDict> selectByUpdUserNm(String updUserNm);

    List<SysDict> selectByUpdTime(java.util.Date updTime);

    List<SysDict> selectByUpdTerminalIp(String updTerminalIp);
}