package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysLog;
import com.kiun.functionary.dao.sys.entity.SysLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogMapper extends com.kiun.functionary.base.BaseExampleMapper<SysLogExample, SysLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     * 2023-07-23 22:37:00
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     * 2023-07-23 22:37:00
     */
    SysLog selectByPrimaryKey(String logId);

    List<SysLog> selectByLogId(String logId);

    List<SysLog> selectByLoginName(String loginName);

    List<SysLog> selectByModuleId(String moduleId);

    List<SysLog> selectByRegId(String regId);

    List<SysLog> selectByLogValue(String logValue);

    List<SysLog> selectByRemark(String remark);

    List<SysLog> selectByCreaterId(String createrId);

    List<SysLog> selectByCreateDate(String createDate);

    List<SysLog> selectByCreateTime(String createTime);
}