package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysLog;
import com.kiun.functionary.dao.sys.entity.SysLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogMapper extends com.kiun.functionary.base.BaseExampleMapper<SysLogExample, SysLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     * 2023-09-13 00:30:58
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     * 2023-09-13 00:30:58
     */
    SysLog selectByPrimaryKey(String logId);

    List<SysLog> selectByLogId(String logId);

    List<SysLog> selectByTitle(String title);

    List<SysLog> selectByModuleId(String moduleId);

    List<SysLog> selectByDeviceName(String deviceName);

    List<SysLog> selectByRegId(String regId);

    List<SysLog> selectByLogValue(String logValue);

    List<SysLog> selectByAddUserId(String addUserId);

    List<SysLog> selectByAddUserNm(String addUserNm);

    List<SysLog> selectByAddTime(java.util.Date addTime);

    List<SysLog> selectByUpdUserId(String updUserId);

    List<SysLog> selectByUpdUserNm(String updUserNm);

    List<SysLog> selectByUpdTime(java.util.Date updTime);

    List<SysLog> selectByUpdTerminalIp(String updTerminalIp);
}