package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysOrgan;
import com.kiun.functionary.dao.sys.entity.SysOrganExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOrganMapper extends com.kiun.functionary.base.BaseExampleMapper<SysOrganExample, SysOrgan> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organ
     * 2023-08-02 21:27:48
     */
    int deleteByPrimaryKey(String organId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organ
     * 2023-08-02 21:27:48
     */
    SysOrgan selectByPrimaryKey(String organId);

    List<SysOrgan> selectByOrganId(String organId);

    List<SysOrgan> selectByOrganName(String organName);

    List<SysOrgan> selectByOrganType(String organType);

    List<SysOrgan> selectByParentId(String parentId);

    List<SysOrgan> selectByAddress(String address);

    List<SysOrgan> selectByPostNo(String postNo);

    List<SysOrgan> selectByPhoneNo(String phoneNo);

    List<SysOrgan> selectByFaxNo(String faxNo);

    List<SysOrgan> selectByRangCd(String rangCd);

    List<SysOrgan> selectByRangId(String rangId);

    List<SysOrgan> selectByAddUserId(String addUserId);

    List<SysOrgan> selectByAddUserNm(String addUserNm);

    List<SysOrgan> selectByAddTime(java.util.Date addTime);

    List<SysOrgan> selectByUpdUserId(String updUserId);

    List<SysOrgan> selectByUpdUserNm(String updUserNm);

    List<SysOrgan> selectByUpdTime(java.util.Date updTime);

    List<SysOrgan> selectByUpdTerminalIp(String updTerminalIp);
}