package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysRole;
import com.kiun.functionary.dao.sys.entity.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper extends com.kiun.functionary.base.BaseExampleMapper<SysRoleExample, SysRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     * 2023-07-10 20:55:36
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     * 2023-07-10 20:55:36
     */
    SysRole selectByPrimaryKey(String roleId);

    List<SysRole> selectByRoleId(String roleId);

    List<SysRole> selectByRoleName(String roleName);

    List<SysRole> selectByRoleType(String roleType);

    List<SysRole> selectByRemark(String remark);

    List<SysRole> selectByCreaterId(String createrId);

    List<SysRole> selectByCreateDate(String createDate);

    List<SysRole> selectByCreateTime(String createTime);

    List<SysRole> selectByUpdateId(String updateId);

    List<SysRole> selectByUpdateDate(String updateDate);

    List<SysRole> selectByUpdateTime(String updateTime);
}