package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysResource;
import com.kiun.functionary.dao.sys.entity.SysResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysResourceMapper extends com.kiun.functionary.base.BaseExampleMapper<SysResourceExample, SysResource> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     * 2023-07-10 20:55:36
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     * 2023-07-10 20:55:36
     */
    SysResource selectByPrimaryKey(String resourceId);

    List<SysResource> selectByResourceId(String resourceId);

    List<SysResource> selectByUrl(String url);

    List<SysResource> selectByTitle(String title);

    List<SysResource> selectByResSizeX(Integer resSizeX);

    List<SysResource> selectByResSizeY(Integer resSizeY);

    List<SysResource> selectByCreateId(String createId);
}