package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysRole;
import com.kiun.functionary.dao.sys.entity.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper extends com.kiun.functionary.base.BaseExampleMapper<SysRoleExample, SysRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     * 2023-08-02 22:48:51
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     * 2023-08-02 22:48:51
     */
    SysRole selectByPrimaryKey(String roleId);

    List<SysRole> selectByRoleId(String roleId);

    List<SysRole> selectByRoleName(String roleName);

    List<SysRole> selectByRoleType(String roleType);

    List<SysRole> selectByRemark(String remark);

    List<SysRole> selectByAddUserId(String addUserId);

    List<SysRole> selectByAddUserNm(String addUserNm);

    List<SysRole> selectByAddTime(java.util.Date addTime);

    List<SysRole> selectByUpdUserId(String updUserId);

    List<SysRole> selectByUpdUserNm(String updUserNm);

    List<SysRole> selectByUpdTime(java.util.Date updTime);

    List<SysRole> selectByUpdTerminalIp(String updTerminalIp);
}