package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysUser;
import com.kiun.functionary.dao.sys.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper extends BaseExampleMapper<SysUserExample, SysUser> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    SysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    int updateByPrimaryKey(SysUser record);

    List<SysUser> selectByUserId(String userId);

    List<SysUser> selectByLoginName(String loginName);

    List<SysUser> selectByLoginPwd(String loginPwd);

    List<SysUser> selectBySalt(String salt);

    List<SysUser> selectByUserName(String userName);

    List<SysUser> selectByModifyLoginPwd(String modifyLoginPwd);

    List<SysUser> selectByFailedLoginNum(Integer failedLoginNum);

    List<SysUser> selectByMaxLoginNum(Integer maxLoginNum);

    List<SysUser> selectByPwdExpiryDay(Integer pwdExpiryDay);

    List<SysUser> selectByLastPwdUpdateDate(String lastPwdUpdateDate);

    List<SysUser> selectByLastPwdUpdateTime(String lastPwdUpdateTime);

    List<SysUser> selectByUserType(String userType);

    List<SysUser> selectByStatus(String status);

    List<SysUser> selectByRepeatLoginFlag(String repeatLoginFlag);

    List<SysUser> selectByEmail(String email);

    List<SysUser> selectByMobileNo(String mobileNo);

    List<SysUser> selectByHomeNo(String homeNo);

    List<SysUser> selectByOfficeNo(String officeNo);

    List<SysUser> selectByAddress(String address);

    List<SysUser> selectByRemark(String remark);

    List<SysUser> selectByCreaterId(String createrId);

    List<SysUser> selectByCreateDate(String createDate);

    List<SysUser> selectByUpdateId(String updateId);

    List<SysUser> selectByUpdateDate(String updateDate);

    List<SysUser> selectByOwnerOrgan(String ownerOrgan);

    List<SysUser> selectByCreateTime(String createTime);

    List<SysUser> selectByUpdateTime(String updateTime);
}
