package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysUser;
import com.kiun.functionary.dao.sys.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper extends com.kiun.functionary.base.BaseExampleMapper<SysUserExample, SysUser> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    SysUser selectByPrimaryKey(String userId);

    List<SysUser> selectByUserId(String userId);

    List<SysUser> selectByLoginName(String loginName);

    List<SysUser> selectByLoginPwd(String loginPwd);

    List<SysUser> selectBySalt(String salt);

    List<SysUser> selectByUserName(String userName);

    List<SysUser> selectByFailedLoginNum(Integer failedLoginNum);

    List<SysUser> selectByMaxLoginNum(Integer maxLoginNum);

    List<SysUser> selectByPwdExpiryDay(Integer pwdExpiryDay);

    List<SysUser> selectByUserType(String userType);

    List<SysUser> selectByStatus(String status);

    List<SysUser> selectByEmail(String email);

    List<SysUser> selectByMobileNo(String mobileNo);

    List<SysUser> selectByHomeNo(String homeNo);

    List<SysUser> selectByOfficeNo(String officeNo);

    List<SysUser> selectByAddress(String address);

    List<SysUser> selectByRemark(String remark);

    List<SysUser> selectByAddUserId(String addUserId);

    List<SysUser> selectByAddUserNm(String addUserNm);

    List<SysUser> selectByAddTime(java.util.Date addTime);

    List<SysUser> selectByUpdUserId(String updUserId);

    List<SysUser> selectByUpdUserNm(String updUserNm);

    List<SysUser> selectByUpdTime(java.util.Date updTime);

    List<SysUser> selectByUpdTerminalIp(String updTerminalIp);
}