package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysUserRoleEle;
import com.kiun.functionary.dao.sys.entity.SysUserRoleEleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRoleEleMapper extends com.kiun.functionary.base.BaseExampleMapper<SysUserRoleEleExample, SysUserRoleEle> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_ele
     * 2023-07-10 20:55:36
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("roleId") String roleId);

    List<SysUserRoleEle> selectByUserId(String userId);

    List<SysUserRoleEle> selectByRoleId(String roleId);
}