package com.kiun.functionary.dao.lz.entity;

import com.kiun.functionary.base.Criterion;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BettingHeadExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2024-05-26 11:13:22
     */
    protected boolean distinct;

    /**
     * 2024-05-26 11:13:22
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public BettingHeadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lz_betting_head
     * 2024-05-26 11:13:22
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBettingCountIsNull() {
            addCriterion("betting_count is null");
            return (Criteria) this;
        }

        public Criteria andBettingCountIsNotNull() {
            addCriterion("betting_count is not null");
            return (Criteria) this;
        }

        public Criteria andBettingCountEqualTo(Integer value) {
            addCriterion("betting_count =", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountNotEqualTo(Integer value) {
            addCriterion("betting_count <>", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountGreaterThan(Integer value) {
            addCriterion("betting_count >", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("betting_count >=", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountLessThan(Integer value) {
            addCriterion("betting_count <", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountLessThanOrEqualTo(Integer value) {
            addCriterion("betting_count <=", value, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountIn(List<Integer> values) {
            addCriterion("betting_count in", values, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountNotIn(List<Integer> values) {
            addCriterion("betting_count not in", values, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountBetween(Integer value1, Integer value2) {
            addCriterion("betting_count between", value1, value2, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingCountNotBetween(Integer value1, Integer value2) {
            addCriterion("betting_count not between", value1, value2, "bettingCount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountIsNull() {
            addCriterion("betting_amount is null");
            return (Criteria) this;
        }

        public Criteria andBettingAmountIsNotNull() {
            addCriterion("betting_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBettingAmountEqualTo(BigDecimal value) {
            addCriterion("betting_amount =", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountNotEqualTo(BigDecimal value) {
            addCriterion("betting_amount <>", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountGreaterThan(BigDecimal value) {
            addCriterion("betting_amount >", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("betting_amount >=", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountLessThan(BigDecimal value) {
            addCriterion("betting_amount <", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("betting_amount <=", value, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountIn(List<BigDecimal> values) {
            addCriterion("betting_amount in", values, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountNotIn(List<BigDecimal> values) {
            addCriterion("betting_amount not in", values, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betting_amount between", value1, value2, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betting_amount not between", value1, value2, "bettingAmount");
            return (Criteria) this;
        }

        public Criteria andBettingTimeIsNull() {
            addCriterion("betting_time is null");
            return (Criteria) this;
        }

        public Criteria andBettingTimeIsNotNull() {
            addCriterion("betting_time is not null");
            return (Criteria) this;
        }

        public Criteria andBettingTimeEqualTo(Date value) {
            addCriterion("betting_time =", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeNotEqualTo(Date value) {
            addCriterion("betting_time <>", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeGreaterThan(Date value) {
            addCriterion("betting_time >", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("betting_time >=", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeLessThan(Date value) {
            addCriterion("betting_time <", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeLessThanOrEqualTo(Date value) {
            addCriterion("betting_time <=", value, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeIn(List<Date> values) {
            addCriterion("betting_time in", values, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeNotIn(List<Date> values) {
            addCriterion("betting_time not in", values, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeBetween(Date value1, Date value2) {
            addCriterion("betting_time between", value1, value2, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTimeNotBetween(Date value1, Date value2) {
            addCriterion("betting_time not between", value1, value2, "bettingTime");
            return (Criteria) this;
        }

        public Criteria andBettingTypeIsNull() {
            addCriterion("betting_type is null");
            return (Criteria) this;
        }

        public Criteria andBettingTypeIsNotNull() {
            addCriterion("betting_type is not null");
            return (Criteria) this;
        }

        public Criteria andBettingTypeEqualTo(String value) {
            addCriterion("betting_type =", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeNotEqualTo(String value) {
            addCriterion("betting_type <>", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeGreaterThan(String value) {
            addCriterion("betting_type >", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("betting_type >=", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeLessThan(String value) {
            addCriterion("betting_type <", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeLessThanOrEqualTo(String value) {
            addCriterion("betting_type <=", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeLike(String value) {
            addCriterion("betting_type like", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeNotLike(String value) {
            addCriterion("betting_type not like", value, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeIn(List<String> values) {
            addCriterion("betting_type in", values, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeNotIn(List<String> values) {
            addCriterion("betting_type not in", values, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeBetween(String value1, String value2) {
            addCriterion("betting_type between", value1, value2, "bettingType");
            return (Criteria) this;
        }

        public Criteria andBettingTypeNotBetween(String value1, String value2) {
            addCriterion("betting_type not between", value1, value2, "bettingType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lz_betting_head
     * do_not_delete_during_merge 2024-05-26 11:13:22
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}