package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.AgencyRecord;
import com.kiun.functionary.dao.gks.entity.AgencyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgencyRecordMapper extends com.kiun.functionary.base.BaseExampleMapper<AgencyRecordExample, AgencyRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_agency_record
     * 2023-12-27 14:36:59
     */
    int deleteByPrimaryKey(@Param("agencyId") String agencyId, @Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_agency_record
     * 2023-12-27 14:36:59
     */
    AgencyRecord selectByPrimaryKey(@Param("agencyId") String agencyId, @Param("userId") String userId);

    List<AgencyRecord> selectByAgencyId(String agencyId);

    List<AgencyRecord> selectByUserId(String userId);

    List<AgencyRecord> selectByAgencyName(String agencyName);

    List<AgencyRecord> selectByAddUserId(String addUserId);

    List<AgencyRecord> selectByAddUserNm(String addUserNm);

    List<AgencyRecord> selectByAddTime(java.util.Date addTime);

    List<AgencyRecord> selectByUpdUserId(String updUserId);

    List<AgencyRecord> selectByUpdUserNm(String updUserNm);

    List<AgencyRecord> selectByUpdTime(java.util.Date updTime);

    List<AgencyRecord> selectByUpdTerminalIp(String updTerminalIp);
}