package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.Feedback;
import com.kiun.functionary.dao.gks.entity.FeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackMapper extends com.kiun.functionary.base.BaseExampleMapper<FeedbackExample, Feedback> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_feedback
     * 2023-09-27 17:17:31
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_feedback
     * 2023-09-27 17:17:31
     */
    Feedback selectByPrimaryKey(String id);

    List<Feedback> selectById(String id);

    List<Feedback> selectByFeedback(String feedback);

    List<Feedback> selectByAddUserId(String addUserId);

    List<Feedback> selectByAddUserNm(String addUserNm);

    List<Feedback> selectByAddTime(java.util.Date addTime);

    List<Feedback> selectByUpdUserId(String updUserId);

    List<Feedback> selectByUpdUserNm(String updUserNm);

    List<Feedback> selectByUpdTime(java.util.Date updTime);

    List<Feedback> selectByUpdTerminalIp(String updTerminalIp);
}