package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.ImportPlan;
import com.kiun.functionary.dao.gks.entity.ImportPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImportPlanMapper extends com.kiun.functionary.base.BaseExampleMapper<ImportPlanExample, ImportPlan> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_import_plan
     * 2023-11-11 21:57:49
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_import_plan
     * 2023-11-11 21:57:49
     */
    ImportPlan selectByPrimaryKey(String id);

    List<ImportPlan> selectById(String id);

    List<ImportPlan> selectByTitle(String title);

    List<ImportPlan> selectByHeadIndex(Integer headIndex);

    List<ImportPlan> selectBySheetField(String sheetField);

    List<ImportPlan> selectByPlanDesc(String planDesc);

    List<ImportPlan> selectByAddUserId(String addUserId);

    List<ImportPlan> selectByAddUserNm(String addUserNm);

    List<ImportPlan> selectByAddTime(java.util.Date addTime);

    List<ImportPlan> selectByUpdUserId(String updUserId);

    List<ImportPlan> selectByUpdUserNm(String updUserNm);

    List<ImportPlan> selectByUpdTime(java.util.Date updTime);

    List<ImportPlan> selectByUpdTerminalIp(String updTerminalIp);
}