package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.ImportPlanColumn;
import com.kiun.functionary.dao.gks.entity.ImportPlanColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImportPlanColumnMapper extends com.kiun.functionary.base.BaseExampleMapper<ImportPlanColumnExample, ImportPlanColumn> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_plan_column
     * 2023-11-13 09:15:20
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_plan_column
     * 2023-11-13 09:15:20
     */
    ImportPlanColumn selectByPrimaryKey(String id);

    List<ImportPlanColumn> selectById(String id);

    List<ImportPlanColumn> selectByPlanId(String planId);

    List<ImportPlanColumn> selectByColumnIndex(Integer columnIndex);

    List<ImportPlanColumn> selectByColumnField(String columnField);

    List<ImportPlanColumn> selectByColumnTitle(String columnTitle);

    List<ImportPlanColumn> selectByColumnFormat(String columnFormat);

    List<ImportPlanColumn> selectByAddUserId(String addUserId);

    List<ImportPlanColumn> selectByAddUserNm(String addUserNm);

    List<ImportPlanColumn> selectByAddTime(java.util.Date addTime);

    List<ImportPlanColumn> selectByUpdUserId(String updUserId);

    List<ImportPlanColumn> selectByUpdUserNm(String updUserNm);

    List<ImportPlanColumn> selectByUpdTime(java.util.Date updTime);

    List<ImportPlanColumn> selectByUpdTerminalIp(String updTerminalIp);
}