package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.JobDetails;
import com.kiun.functionary.dao.gks.entity.JobDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobDetailsMapper extends com.kiun.functionary.base.BaseExampleMapper<JobDetailsExample, JobDetails> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_details
     * 2023-08-08 23:13:18
     */
    JobDetails selectByPrimaryKey(String id);

    List<JobDetails> selectById(String id);

    List<JobDetails> selectByJobNotice(String jobNotice);

    List<JobDetails> selectByJobName(String jobName);

    List<JobDetails> selectByJobCount(Integer jobCount);

    List<JobDetails> selectByJobSalary(java.math.BigDecimal jobSalary);

    List<JobDetails> selectByJobRequire(String jobRequire);

    List<JobDetails> selectByJobWork(String jobWork);

    List<JobDetails> selectByFactorSpeciality(String factorSpeciality);

    List<JobDetails> selectByFactorEducation(String factorEducation);

    List<JobDetails> selectByFactorGender(String factorGender);

    List<JobDetails> selectByFactorDomicile(String factorDomicile);

    List<JobDetails> selectByFactorAgeMax(Integer factorAgeMax);

    List<JobDetails> selectByFactorAgeMin(Integer factorAgeMin);

    List<JobDetails> selectByFactorDesc(String factorDesc);

    List<JobDetails> selectByAddUserId(String addUserId);

    List<JobDetails> selectByAddUserNm(String addUserNm);

    List<JobDetails> selectByAddTime(java.util.Date addTime);

    List<JobDetails> selectByUpdUserId(String updUserId);

    List<JobDetails> selectByUpdUserNm(String updUserNm);

    List<JobDetails> selectByUpdTime(java.util.Date updTime);

    List<JobDetails> selectByUpdTerminalIp(String updTerminalIp);
}