package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.JobMust;
import com.kiun.functionary.dao.gks.entity.JobMustExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobMustMapper extends com.kiun.functionary.base.BaseExampleMapper<JobMustExample, JobMust> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    int deleteByPrimaryKey(@Param("jobId") String jobId, @Param("dictItemId") String dictItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_must
     * 2023-10-11 08:32:41
     */
    JobMust selectByPrimaryKey(@Param("jobId") String jobId, @Param("dictItemId") String dictItemId);

    List<JobMust> selectByJobId(String jobId);

    List<JobMust> selectByDictItemId(String dictItemId);

    List<JobMust> selectByNoticeId(String noticeId);

    List<JobMust> selectByDictItemKey(String dictItemKey);

    List<JobMust> selectByDictItemValue(String dictItemValue);

    List<JobMust> selectByDictId(String dictId);
}