package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.JobNotice;
import com.kiun.functionary.dao.gks.entity.JobNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobNoticeMapper extends com.kiun.functionary.base.BaseExampleMapper<JobNoticeExample, JobNotice> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_notice
     * 2023-08-08 23:07:12
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gks_job_notice
     * 2023-08-08 23:07:12
     */
    JobNotice selectByPrimaryKey(String id);

    List<JobNotice> selectById(String id);

    List<JobNotice> selectByTitle(String title);

    List<JobNotice> selectByPublishTime(java.util.Date publishTime);

    List<JobNotice> selectByOrganId(String organId);

    List<JobNotice> selectByInfoUrl(String infoUrl);

    List<JobNotice> selectByJobUrl(String jobUrl);

    List<JobNotice> selectByDetailUrl(String detailUrl);

    List<JobNotice> selectByAddUserId(String addUserId);

    List<JobNotice> selectByAddUserNm(String addUserNm);

    List<JobNotice> selectByAddTime(java.util.Date addTime);

    List<JobNotice> selectByUpdUserId(String updUserId);

    List<JobNotice> selectByUpdUserNm(String updUserNm);

    List<JobNotice> selectByUpdTime(java.util.Date updTime);

    List<JobNotice> selectByUpdTerminalIp(String updTerminalIp);
}