package com.kiun.functionary.dao.gks;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.gks.entity.VJobNoticeDetails;
import com.kiun.functionary.dao.gks.entity.VJobNoticeDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VJobNoticeDetailsMapper extends com.kiun.functionary.base.BaseExampleMapper<VJobNoticeDetailsExample, VJobNoticeDetails> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_notice_details
     * 2023-09-12 19:52:33
     */
    List<VJobNoticeDetails> selectByExampleWithBLOBs(VJobNoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_gks_job_notice_details
     * 2023-09-12 19:52:33
     */
    int updateByExampleWithBLOBs(@Param("record") VJobNoticeDetails record, @Param("example") VJobNoticeDetailsExample example);

    List<VJobNoticeDetails> selectById(String id);

    List<VJobNoticeDetails> selectByTitle(String title);

    List<VJobNoticeDetails> selectByPublishTime(java.util.Date publishTime);

    List<VJobNoticeDetails> selectByStartTime(java.util.Date startTime);

    List<VJobNoticeDetails> selectByEndTime(java.util.Date endTime);

    List<VJobNoticeDetails> selectByOrganId(String organId);

    List<VJobNoticeDetails> selectByOrganName(String organName);

    List<VJobNoticeDetails> selectByJobCount(java.math.BigDecimal jobCount);

    List<VJobNoticeDetails> selectByCount(Long count);

    List<VJobNoticeDetails> selectByDetails(String details);

    List<VJobNoticeDetails> selectByInfoUrl(String infoUrl);

    List<VJobNoticeDetails> selectByJobUrl(String jobUrl);

    List<VJobNoticeDetails> selectByDetailUrl(String detailUrl);
}