package com.kiun.functionary.dao.sys.entity;

import com.kiun.functionary.dao.IdRandom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 字典项
 * 
 * sys_dict
 *
 * 2023-07-10 20:55:36
 */
@ApiModel(description="字典项")
public class SysDict extends IdRandom {
    /**
     * 字典ID
     */
    @ApiModelProperty("字典ID")
    private String dictId;

    /**
     * 字典名称
     */
    @ApiModelProperty("字典名称")
    private String dictName;

    /**
     * 父字典
     */
    @ApiModelProperty("父字典")
    private String groupDict;

    public String getDictId() {
        return dictId;
    }

    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    public String getDictName() {
        return dictName;
    }

    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    public String getGroupDict() {
        return groupDict;
    }

    public void setGroupDict(String groupDict) {
        this.groupDict = groupDict == null ? null : groupDict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-10 20:55:36
     */
    public void setId(String id) {
        this.dictId=id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-10 20:55:36
     */
    public String getId() {
        return dictId;
    }
}