package com.kiun.functionary.dao.sys.entity;

import com.kiun.functionary.base.general.*;
import com.kiun.functionary.dao.IdRandom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * 字典项
 *
 * sys_dict
 *
 * 2023-07-26 21:14:35
 */
@ApiModel(description="字典项")
@ListBuild(value = "SysDict", title = "字典项", operate = {
        @Operate(title = "删除", function = "removeAll", color = ButtonColor.Danger, icon = "fa-remove", toolbar = true),
        @Operate(title = "添加", url = "/general/add/@{formId}", icon = "fa-plus", toolbar = true),
        @Operate(title = "编辑", url = "/general/edit/SysDict/{id}"),
        @Operate(title = "编辑子项", url = "/general/tree/VSysDictItemTree?dictId={id}&dictName={dictName}&parentCode=parentId&code=id"),
        @Operate(title = "删除", url = "remove", function = "remove", color = ButtonColor.Danger, icon = "fa-remove")
})
public class SysDict extends IdRandom {

    /**
     * 字典ID
     */
    @ApiModelProperty("字典标识")
    @ListBuildItem(title = "字典标识")
    private String dictId;

    /**
     * 字典名称
     */
    @ApiModelProperty("字典名称")
    @ListBuildItem(title = "字典名称")
    private String dictName;

    /**
     * 父字典
     */
    @ApiModelProperty("父字典")
    @ListBuildItem(title = "父字典")
    private String groupDict;

    /**
     * 添加用户ID
     */
    @ApiModelProperty("添加用户ID")
    private String addUserId;

    /**
     * 添加用户名称
     */
    @ApiModelProperty("添加用户名称")
    @ListBuildItem(title = "添加用户", flag = FormFlag.Search | FormFlag.Table)
    private String addUserNm;

    /**
     * 添加时间
     */
    @ApiModelProperty("添加时间")
    @ListBuildItem(title = "添加时间", flag = FormFlag.Search | FormFlag.Table)
    private Date addTime;

    /**
     * 修改用户ID
     */
    @ApiModelProperty("修改用户ID")
    private String updUserId;

    /**
     * 修改用户名称
     */
    @ApiModelProperty("修改用户名称")
    @ListBuildItem(title = "修改用户", flag = FormFlag.Table)
    private String updUserNm;

    /**
     * 修改用户时间
     */
    @ApiModelProperty("修改用户时间")
    @ListBuildItem(title = "修改时间", flag = FormFlag.Table)
    private Date updTime;

    /**
     * 修改数据人员IP
     */
    @ApiModelProperty("修改数据人员IP")
    @ListBuildItem(title = "操作终端", flag = FormFlag.Table)
    private String updTerminalIp;

    public String getDictId() {
        return dictId;
    }

    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    public String getDictName() {
        return dictName;
    }

    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    public String getGroupDict() {
        return groupDict;
    }

    public void setGroupDict(String groupDict) {
        this.groupDict = groupDict == null ? null : groupDict.trim();
    }

    public String getAddUserId() {
        return addUserId;
    }

    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    public String getAddUserNm() {
        return addUserNm;
    }

    public void setAddUserNm(String addUserNm) {
        this.addUserNm = addUserNm == null ? null : addUserNm.trim();
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getUpdUserId() {
        return updUserId;
    }

    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId == null ? null : updUserId.trim();
    }

    public String getUpdUserNm() {
        return updUserNm;
    }

    public void setUpdUserNm(String updUserNm) {
        this.updUserNm = updUserNm == null ? null : updUserNm.trim();
    }

    public Date getUpdTime() {
        return updTime;
    }

    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    public String getUpdTerminalIp() {
        return updTerminalIp;
    }

    public void setUpdTerminalIp(String updTerminalIp) {
        this.updTerminalIp = updTerminalIp == null ? null : updTerminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-26 21:14:35
     */
    public void setId(String id) {
        this.dictId=id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-26 21:14:35
     */
    public String getId() {
        return dictId;
    }
}
