package com.kiun.functionary.dao.sys.entity;

import com.kiun.functionary.base.Criterion;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-09-05 22:13:52
     */
    protected boolean distinct;

    /**
     * 2023-09-05 22:13:52
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     * 2023-09-05 22:13:52
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNull() {
            addCriterion("login_pwd is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNotNull() {
            addCriterion("login_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdEqualTo(String value) {
            addCriterion("login_pwd =", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotEqualTo(String value) {
            addCriterion("login_pwd <>", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThan(String value) {
            addCriterion("login_pwd >", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("login_pwd >=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThan(String value) {
            addCriterion("login_pwd <", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("login_pwd <=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLike(String value) {
            addCriterion("login_pwd like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotLike(String value) {
            addCriterion("login_pwd not like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIn(List<String> values) {
            addCriterion("login_pwd in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotIn(List<String> values) {
            addCriterion("login_pwd not in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdBetween(String value1, String value2) {
            addCriterion("login_pwd between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotBetween(String value1, String value2) {
            addCriterion("login_pwd not between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIsNull() {
            addCriterion("failed_login_num is null");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIsNotNull() {
            addCriterion("failed_login_num is not null");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumEqualTo(Integer value) {
            addCriterion("failed_login_num =", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotEqualTo(Integer value) {
            addCriterion("failed_login_num <>", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumGreaterThan(Integer value) {
            addCriterion("failed_login_num >", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("failed_login_num >=", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumLessThan(Integer value) {
            addCriterion("failed_login_num <", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumLessThanOrEqualTo(Integer value) {
            addCriterion("failed_login_num <=", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIn(List<Integer> values) {
            addCriterion("failed_login_num in", values, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotIn(List<Integer> values) {
            addCriterion("failed_login_num not in", values, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumBetween(Integer value1, Integer value2) {
            addCriterion("failed_login_num between", value1, value2, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotBetween(Integer value1, Integer value2) {
            addCriterion("failed_login_num not between", value1, value2, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIsNull() {
            addCriterion("max_login_num is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIsNotNull() {
            addCriterion("max_login_num is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumEqualTo(Integer value) {
            addCriterion("max_login_num =", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotEqualTo(Integer value) {
            addCriterion("max_login_num <>", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumGreaterThan(Integer value) {
            addCriterion("max_login_num >", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_login_num >=", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumLessThan(Integer value) {
            addCriterion("max_login_num <", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumLessThanOrEqualTo(Integer value) {
            addCriterion("max_login_num <=", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIn(List<Integer> values) {
            addCriterion("max_login_num in", values, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotIn(List<Integer> values) {
            addCriterion("max_login_num not in", values, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumBetween(Integer value1, Integer value2) {
            addCriterion("max_login_num between", value1, value2, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotBetween(Integer value1, Integer value2) {
            addCriterion("max_login_num not between", value1, value2, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIsNull() {
            addCriterion("pwd_expiry_day is null");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIsNotNull() {
            addCriterion("pwd_expiry_day is not null");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayEqualTo(Integer value) {
            addCriterion("pwd_expiry_day =", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotEqualTo(Integer value) {
            addCriterion("pwd_expiry_day <>", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayGreaterThan(Integer value) {
            addCriterion("pwd_expiry_day >", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("pwd_expiry_day >=", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayLessThan(Integer value) {
            addCriterion("pwd_expiry_day <", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayLessThanOrEqualTo(Integer value) {
            addCriterion("pwd_expiry_day <=", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIn(List<Integer> values) {
            addCriterion("pwd_expiry_day in", values, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotIn(List<Integer> values) {
            addCriterion("pwd_expiry_day not in", values, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayBetween(Integer value1, Integer value2) {
            addCriterion("pwd_expiry_day between", value1, value2, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotBetween(Integer value1, Integer value2) {
            addCriterion("pwd_expiry_day not between", value1, value2, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("user_type like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("user_type not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("mobile_no is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("mobile_no is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("mobile_no =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("mobile_no <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("mobile_no >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_no >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("mobile_no <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("mobile_no <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("mobile_no like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("mobile_no not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("mobile_no in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("mobile_no not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("mobile_no between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("mobile_no not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoIsNull() {
            addCriterion("home_no is null");
            return (Criteria) this;
        }

        public Criteria andHomeNoIsNotNull() {
            addCriterion("home_no is not null");
            return (Criteria) this;
        }

        public Criteria andHomeNoEqualTo(String value) {
            addCriterion("home_no =", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotEqualTo(String value) {
            addCriterion("home_no <>", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoGreaterThan(String value) {
            addCriterion("home_no >", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoGreaterThanOrEqualTo(String value) {
            addCriterion("home_no >=", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLessThan(String value) {
            addCriterion("home_no <", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLessThanOrEqualTo(String value) {
            addCriterion("home_no <=", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLike(String value) {
            addCriterion("home_no like", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotLike(String value) {
            addCriterion("home_no not like", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoIn(List<String> values) {
            addCriterion("home_no in", values, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotIn(List<String> values) {
            addCriterion("home_no not in", values, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoBetween(String value1, String value2) {
            addCriterion("home_no between", value1, value2, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotBetween(String value1, String value2) {
            addCriterion("home_no not between", value1, value2, "homeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNull() {
            addCriterion("office_no is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNotNull() {
            addCriterion("office_no is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoEqualTo(String value) {
            addCriterion("office_no =", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotEqualTo(String value) {
            addCriterion("office_no <>", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThan(String value) {
            addCriterion("office_no >", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThanOrEqualTo(String value) {
            addCriterion("office_no >=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThan(String value) {
            addCriterion("office_no <", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThanOrEqualTo(String value) {
            addCriterion("office_no <=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLike(String value) {
            addCriterion("office_no like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotLike(String value) {
            addCriterion("office_no not like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIn(List<String> values) {
            addCriterion("office_no in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotIn(List<String> values) {
            addCriterion("office_no not in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoBetween(String value1, String value2) {
            addCriterion("office_no between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotBetween(String value1, String value2) {
            addCriterion("office_no not between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNull() {
            addCriterion("add_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNotNull() {
            addCriterion("add_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdEqualTo(String value) {
            addCriterion("add_user_id =", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotEqualTo(String value) {
            addCriterion("add_user_id <>", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThan(String value) {
            addCriterion("add_user_id >", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_id >=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThan(String value) {
            addCriterion("add_user_id <", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_user_id <=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLike(String value) {
            addCriterion("add_user_id like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotLike(String value) {
            addCriterion("add_user_id not like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIn(List<String> values) {
            addCriterion("add_user_id in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotIn(List<String> values) {
            addCriterion("add_user_id not in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdBetween(String value1, String value2) {
            addCriterion("add_user_id between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotBetween(String value1, String value2) {
            addCriterion("add_user_id not between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNull() {
            addCriterion("add_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIsNotNull() {
            addCriterion("add_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserNmEqualTo(String value) {
            addCriterion("add_user_nm =", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotEqualTo(String value) {
            addCriterion("add_user_nm <>", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThan(String value) {
            addCriterion("add_user_nm >", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_nm >=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThan(String value) {
            addCriterion("add_user_nm <", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLessThanOrEqualTo(String value) {
            addCriterion("add_user_nm <=", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmLike(String value) {
            addCriterion("add_user_nm like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotLike(String value) {
            addCriterion("add_user_nm not like", value, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmIn(List<String> values) {
            addCriterion("add_user_nm in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotIn(List<String> values) {
            addCriterion("add_user_nm not in", values, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmBetween(String value1, String value2) {
            addCriterion("add_user_nm between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddUserNmNotBetween(String value1, String value2) {
            addCriterion("add_user_nm not between", value1, value2, "addUserNm");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("upd_user_id =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("upd_user_id <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("upd_user_id >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_id >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("upd_user_id <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("upd_user_id <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("upd_user_id like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("upd_user_id not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("upd_user_id in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("upd_user_id not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("upd_user_id between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("upd_user_id not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNull() {
            addCriterion("upd_user_nm is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIsNotNull() {
            addCriterion("upd_user_nm is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmEqualTo(String value) {
            addCriterion("upd_user_nm =", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotEqualTo(String value) {
            addCriterion("upd_user_nm <>", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThan(String value) {
            addCriterion("upd_user_nm >", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_nm >=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThan(String value) {
            addCriterion("upd_user_nm <", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLessThanOrEqualTo(String value) {
            addCriterion("upd_user_nm <=", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmLike(String value) {
            addCriterion("upd_user_nm like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotLike(String value) {
            addCriterion("upd_user_nm not like", value, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmIn(List<String> values) {
            addCriterion("upd_user_nm in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotIn(List<String> values) {
            addCriterion("upd_user_nm not in", values, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmBetween(String value1, String value2) {
            addCriterion("upd_user_nm between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdUserNmNotBetween(String value1, String value2) {
            addCriterion("upd_user_nm not between", value1, value2, "updUserNm");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNull() {
            addCriterion("upd_terminal_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIsNotNull() {
            addCriterion("upd_terminal_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpEqualTo(String value) {
            addCriterion("upd_terminal_ip =", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotEqualTo(String value) {
            addCriterion("upd_terminal_ip <>", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThan(String value) {
            addCriterion("upd_terminal_ip >", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpGreaterThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip >=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThan(String value) {
            addCriterion("upd_terminal_ip <", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLessThanOrEqualTo(String value) {
            addCriterion("upd_terminal_ip <=", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpLike(String value) {
            addCriterion("upd_terminal_ip like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotLike(String value) {
            addCriterion("upd_terminal_ip not like", value, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpIn(List<String> values) {
            addCriterion("upd_terminal_ip in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotIn(List<String> values) {
            addCriterion("upd_terminal_ip not in", values, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }

        public Criteria andUpdTerminalIpNotBetween(String value1, String value2) {
            addCriterion("upd_terminal_ip not between", value1, value2, "updTerminalIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     * do_not_delete_during_merge 2023-09-05 22:13:52
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}