package com.kiun.functionary.dao.sys.entity;

import com.kiun.functionary.base.Criterion;
import java.util.ArrayList;
import java.util.List;

public class SysUserExample extends com.kiun.functionary.dao.BaseExample {
    /**
     * 2023-07-09 23:03:19
     */
    protected boolean distinct;

    /**
     * 2023-07-09 23:03:19
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     * 2023-07-09 23:03:19
     */
    protected abstract static class GeneratedCriteria extends com.kiun.functionary.base.BaseCriteria {

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("LOGIN_NAME =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("LOGIN_NAME <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("LOGIN_NAME >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("LOGIN_NAME <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("LOGIN_NAME like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("LOGIN_NAME not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("LOGIN_NAME in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("LOGIN_NAME not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNull() {
            addCriterion("LOGIN_PWD is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNotNull() {
            addCriterion("LOGIN_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdEqualTo(String value) {
            addCriterion("LOGIN_PWD =", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotEqualTo(String value) {
            addCriterion("LOGIN_PWD <>", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThan(String value) {
            addCriterion("LOGIN_PWD >", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD >=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThan(String value) {
            addCriterion("LOGIN_PWD <", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD <=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLike(String value) {
            addCriterion("LOGIN_PWD like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotLike(String value) {
            addCriterion("LOGIN_PWD not like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIn(List<String> values) {
            addCriterion("LOGIN_PWD in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotIn(List<String> values) {
            addCriterion("LOGIN_PWD not in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD not between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("SALT is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("SALT is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("SALT =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("SALT <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("SALT >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("SALT >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("SALT <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("SALT <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("SALT like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("SALT not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("SALT in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("SALT not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("SALT between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("SALT not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdIsNull() {
            addCriterion("MODIFY_LOGIN_PWD is null");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdIsNotNull() {
            addCriterion("MODIFY_LOGIN_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdEqualTo(String value) {
            addCriterion("MODIFY_LOGIN_PWD =", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdNotEqualTo(String value) {
            addCriterion("MODIFY_LOGIN_PWD <>", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdGreaterThan(String value) {
            addCriterion("MODIFY_LOGIN_PWD >", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_LOGIN_PWD >=", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdLessThan(String value) {
            addCriterion("MODIFY_LOGIN_PWD <", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_LOGIN_PWD <=", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdLike(String value) {
            addCriterion("MODIFY_LOGIN_PWD like", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdNotLike(String value) {
            addCriterion("MODIFY_LOGIN_PWD not like", value, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdIn(List<String> values) {
            addCriterion("MODIFY_LOGIN_PWD in", values, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdNotIn(List<String> values) {
            addCriterion("MODIFY_LOGIN_PWD not in", values, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdBetween(String value1, String value2) {
            addCriterion("MODIFY_LOGIN_PWD between", value1, value2, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andModifyLoginPwdNotBetween(String value1, String value2) {
            addCriterion("MODIFY_LOGIN_PWD not between", value1, value2, "modifyLoginPwd");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIsNull() {
            addCriterion("FAILED_LOGIN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIsNotNull() {
            addCriterion("FAILED_LOGIN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumEqualTo(Integer value) {
            addCriterion("FAILED_LOGIN_NUM =", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotEqualTo(Integer value) {
            addCriterion("FAILED_LOGIN_NUM <>", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumGreaterThan(Integer value) {
            addCriterion("FAILED_LOGIN_NUM >", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAILED_LOGIN_NUM >=", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumLessThan(Integer value) {
            addCriterion("FAILED_LOGIN_NUM <", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumLessThanOrEqualTo(Integer value) {
            addCriterion("FAILED_LOGIN_NUM <=", value, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumIn(List<Integer> values) {
            addCriterion("FAILED_LOGIN_NUM in", values, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotIn(List<Integer> values) {
            addCriterion("FAILED_LOGIN_NUM not in", values, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumBetween(Integer value1, Integer value2) {
            addCriterion("FAILED_LOGIN_NUM between", value1, value2, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andFailedLoginNumNotBetween(Integer value1, Integer value2) {
            addCriterion("FAILED_LOGIN_NUM not between", value1, value2, "failedLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIsNull() {
            addCriterion("MAX_LOGIN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIsNotNull() {
            addCriterion("MAX_LOGIN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_NUM =", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_NUM <>", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumGreaterThan(Integer value) {
            addCriterion("MAX_LOGIN_NUM >", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_NUM >=", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumLessThan(Integer value) {
            addCriterion("MAX_LOGIN_NUM <", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_NUM <=", value, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumIn(List<Integer> values) {
            addCriterion("MAX_LOGIN_NUM in", values, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotIn(List<Integer> values) {
            addCriterion("MAX_LOGIN_NUM not in", values, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumBetween(Integer value1, Integer value2) {
            addCriterion("MAX_LOGIN_NUM between", value1, value2, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andMaxLoginNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_LOGIN_NUM not between", value1, value2, "maxLoginNum");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIsNull() {
            addCriterion("PWD_EXPIRY_DAY is null");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIsNotNull() {
            addCriterion("PWD_EXPIRY_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayEqualTo(Integer value) {
            addCriterion("PWD_EXPIRY_DAY =", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotEqualTo(Integer value) {
            addCriterion("PWD_EXPIRY_DAY <>", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayGreaterThan(Integer value) {
            addCriterion("PWD_EXPIRY_DAY >", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("PWD_EXPIRY_DAY >=", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayLessThan(Integer value) {
            addCriterion("PWD_EXPIRY_DAY <", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayLessThanOrEqualTo(Integer value) {
            addCriterion("PWD_EXPIRY_DAY <=", value, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayIn(List<Integer> values) {
            addCriterion("PWD_EXPIRY_DAY in", values, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotIn(List<Integer> values) {
            addCriterion("PWD_EXPIRY_DAY not in", values, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayBetween(Integer value1, Integer value2) {
            addCriterion("PWD_EXPIRY_DAY between", value1, value2, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andPwdExpiryDayNotBetween(Integer value1, Integer value2) {
            addCriterion("PWD_EXPIRY_DAY not between", value1, value2, "pwdExpiryDay");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateIsNull() {
            addCriterion("LAST_PWD_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateIsNotNull() {
            addCriterion("LAST_PWD_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE =", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateNotEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE <>", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateGreaterThan(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE >", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE >=", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateLessThan(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE <", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE <=", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateLike(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE like", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateNotLike(String value) {
            addCriterion("LAST_PWD_UPDATE_DATE not like", value, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateIn(List<String> values) {
            addCriterion("LAST_PWD_UPDATE_DATE in", values, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateNotIn(List<String> values) {
            addCriterion("LAST_PWD_UPDATE_DATE not in", values, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateBetween(String value1, String value2) {
            addCriterion("LAST_PWD_UPDATE_DATE between", value1, value2, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateDateNotBetween(String value1, String value2) {
            addCriterion("LAST_PWD_UPDATE_DATE not between", value1, value2, "lastPwdUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeIsNull() {
            addCriterion("LAST_PWD_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeIsNotNull() {
            addCriterion("LAST_PWD_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME =", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeNotEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME <>", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeGreaterThan(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME >", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME >=", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeLessThan(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME <", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME <=", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeLike(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME like", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeNotLike(String value) {
            addCriterion("LAST_PWD_UPDATE_TIME not like", value, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeIn(List<String> values) {
            addCriterion("LAST_PWD_UPDATE_TIME in", values, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeNotIn(List<String> values) {
            addCriterion("LAST_PWD_UPDATE_TIME not in", values, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeBetween(String value1, String value2) {
            addCriterion("LAST_PWD_UPDATE_TIME between", value1, value2, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("LAST_PWD_UPDATE_TIME not between", value1, value2, "lastPwdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("USER_TYPE like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("USER_TYPE not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagIsNull() {
            addCriterion("REPEAT_LOGIN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagIsNotNull() {
            addCriterion("REPEAT_LOGIN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagEqualTo(String value) {
            addCriterion("REPEAT_LOGIN_FLAG =", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagNotEqualTo(String value) {
            addCriterion("REPEAT_LOGIN_FLAG <>", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagGreaterThan(String value) {
            addCriterion("REPEAT_LOGIN_FLAG >", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagGreaterThanOrEqualTo(String value) {
            addCriterion("REPEAT_LOGIN_FLAG >=", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagLessThan(String value) {
            addCriterion("REPEAT_LOGIN_FLAG <", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagLessThanOrEqualTo(String value) {
            addCriterion("REPEAT_LOGIN_FLAG <=", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagLike(String value) {
            addCriterion("REPEAT_LOGIN_FLAG like", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagNotLike(String value) {
            addCriterion("REPEAT_LOGIN_FLAG not like", value, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagIn(List<String> values) {
            addCriterion("REPEAT_LOGIN_FLAG in", values, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagNotIn(List<String> values) {
            addCriterion("REPEAT_LOGIN_FLAG not in", values, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagBetween(String value1, String value2) {
            addCriterion("REPEAT_LOGIN_FLAG between", value1, value2, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andRepeatLoginFlagNotBetween(String value1, String value2) {
            addCriterion("REPEAT_LOGIN_FLAG not between", value1, value2, "repeatLoginFlag");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("MOBILE_NO is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("MOBILE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("MOBILE_NO =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("MOBILE_NO <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("MOBILE_NO >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("MOBILE_NO <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("MOBILE_NO like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("MOBILE_NO not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("MOBILE_NO in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("MOBILE_NO not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("MOBILE_NO between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("MOBILE_NO not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoIsNull() {
            addCriterion("HOME_NO is null");
            return (Criteria) this;
        }

        public Criteria andHomeNoIsNotNull() {
            addCriterion("HOME_NO is not null");
            return (Criteria) this;
        }

        public Criteria andHomeNoEqualTo(String value) {
            addCriterion("HOME_NO =", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotEqualTo(String value) {
            addCriterion("HOME_NO <>", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoGreaterThan(String value) {
            addCriterion("HOME_NO >", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoGreaterThanOrEqualTo(String value) {
            addCriterion("HOME_NO >=", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLessThan(String value) {
            addCriterion("HOME_NO <", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLessThanOrEqualTo(String value) {
            addCriterion("HOME_NO <=", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoLike(String value) {
            addCriterion("HOME_NO like", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotLike(String value) {
            addCriterion("HOME_NO not like", value, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoIn(List<String> values) {
            addCriterion("HOME_NO in", values, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotIn(List<String> values) {
            addCriterion("HOME_NO not in", values, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoBetween(String value1, String value2) {
            addCriterion("HOME_NO between", value1, value2, "homeNo");
            return (Criteria) this;
        }

        public Criteria andHomeNoNotBetween(String value1, String value2) {
            addCriterion("HOME_NO not between", value1, value2, "homeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNull() {
            addCriterion("OFFICE_NO is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNotNull() {
            addCriterion("OFFICE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoEqualTo(String value) {
            addCriterion("OFFICE_NO =", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotEqualTo(String value) {
            addCriterion("OFFICE_NO <>", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThan(String value) {
            addCriterion("OFFICE_NO >", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_NO >=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThan(String value) {
            addCriterion("OFFICE_NO <", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_NO <=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLike(String value) {
            addCriterion("OFFICE_NO like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotLike(String value) {
            addCriterion("OFFICE_NO not like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIn(List<String> values) {
            addCriterion("OFFICE_NO in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotIn(List<String> values) {
            addCriterion("OFFICE_NO not in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoBetween(String value1, String value2) {
            addCriterion("OFFICE_NO between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotBetween(String value1, String value2) {
            addCriterion("OFFICE_NO not between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNull() {
            addCriterion("CREATER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNotNull() {
            addCriterion("CREATER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdEqualTo(String value) {
            addCriterion("CREATER_ID =", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotEqualTo(String value) {
            addCriterion("CREATER_ID <>", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThan(String value) {
            addCriterion("CREATER_ID >", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATER_ID >=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThan(String value) {
            addCriterion("CREATER_ID <", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThanOrEqualTo(String value) {
            addCriterion("CREATER_ID <=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLike(String value) {
            addCriterion("CREATER_ID like", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotLike(String value) {
            addCriterion("CREATER_ID not like", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIn(List<String> values) {
            addCriterion("CREATER_ID in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotIn(List<String> values) {
            addCriterion("CREATER_ID not in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdBetween(String value1, String value2) {
            addCriterion("CREATER_ID between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotBetween(String value1, String value2) {
            addCriterion("CREATER_ID not between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganIsNull() {
            addCriterion("OWNER_ORGAN is null");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganIsNotNull() {
            addCriterion("OWNER_ORGAN is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganEqualTo(String value) {
            addCriterion("OWNER_ORGAN =", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganNotEqualTo(String value) {
            addCriterion("OWNER_ORGAN <>", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganGreaterThan(String value) {
            addCriterion("OWNER_ORGAN >", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_ORGAN >=", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganLessThan(String value) {
            addCriterion("OWNER_ORGAN <", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganLessThanOrEqualTo(String value) {
            addCriterion("OWNER_ORGAN <=", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganLike(String value) {
            addCriterion("OWNER_ORGAN like", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganNotLike(String value) {
            addCriterion("OWNER_ORGAN not like", value, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganIn(List<String> values) {
            addCriterion("OWNER_ORGAN in", values, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganNotIn(List<String> values) {
            addCriterion("OWNER_ORGAN not in", values, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganBetween(String value1, String value2) {
            addCriterion("OWNER_ORGAN between", value1, value2, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andOwnerOrganNotBetween(String value1, String value2) {
            addCriterion("OWNER_ORGAN not between", value1, value2, "ownerOrgan");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     * do_not_delete_during_merge 2023-07-09 23:03:19
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}