package com.kiun.functionary.dao.sys;

import com.kiun.functionary.base.BaseExampleMapper;
import com.kiun.functionary.dao.sys.entity.SysDict;
import com.kiun.functionary.dao.sys.entity.SysDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDictMapper extends com.kiun.functionary.base.BaseExampleMapper<SysDict, SysDictExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-10 17:23:50
     */
    int deleteByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     * 2023-07-10 17:23:50
     */
    SysDict selectByPrimaryKey(String dictId);

    List<SysDict> selectByDictId(String dictId);

    List<SysDict> selectByDictName(String dictName);

    List<SysDict> selectByGroupDict(String groupDict);
}